"""Seed 180 Situations questions (hand-crafted) - reaches 500 total.
Batches: 45 obs/risk, 45 speed/distance, 45 communication/position, 45 complex.
"""
import asyncio, os, uuid
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()
MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

LETTERS = ["A", "B", "C", "D"]

# Compact format: (no_q, th_q, en_q, [4 opts as (no,th,en)], correct_idx 0-3, diff, no_expl, th_expl, en_expl)
def Q(no_q, th_q, en_q, opts, correct, diff, no_e, th_e, en_e):
    return {
        "q": {"no": no_q, "th": th_q, "en": en_q},
        "opts": [{"no": o[0], "th": o[1], "en": o[2]} for o in opts],
        "correct": LETTERS[correct],
        "difficulty": diff,
        "expl": {"no": no_e, "th": th_e, "en": en_e},
    }

DATA = []

# ===== BATCH 1: OBSERVATION & RISK (45) =====
DATA += [
Q("Hvor bør du se mest når du kjører på landevei?", "ขับถนนชนบทควรมองที่ไหนมากที่สุด?", "Where to look most on rural road?",
  [("Langt fram i vegen", "ไกลข้างหน้า", "Far ahead"), ("Rett foran panseret", "หน้ารถ", "Right before the hood"),
   ("I speilene", "กระจก", "In mirrors"), ("På bilen foran", "รถคันหน้า", "At car ahead")],
  0, "easy", "Langt blikk gir tidlig informasjon.", "มองไกลได้ข้อมูลเร็ว", "Long gaze gives early info."),
Q("Hva er blindsonen?", "มุมอับคืออะไร?", "What is the blind spot?",
  [("Område du ikke ser i speilene", "จุดที่กระจกมองไม่เห็น", "Area mirrors don't cover"), ("Bak bilen", "ด้านหลัง", "Behind car"),
   ("Under bilen", "ใต้รถ", "Under car"), ("I tunnel", "ในอุโมงค์", "In tunnel")],
  0, "easy", "Blindsone = usynlig i speilene; sjekk over skulderen.", "หันมองข้ามไหล่", "Check over shoulder."),
Q("Hvor ofte bør du sjekke speilene?", "ควรดูกระจกบ่อยแค่ไหน?", "How often check mirrors?",
  [("Hvert 5.–10. sekund", "ทุก 5-10 วินาที", "Every 5-10 s"), ("En gang i minuttet", "นาทีละครั้ง", "Once a minute"),
   ("Kun før bremsing", "ก่อนเบรก", "Before brake"), ("Aldri", "ไม่เคย", "Never")],
  0, "easy", "Jevnlig speilbruk holder oversikten.", "ดูกระจกสม่ำเสมอ", "Regular mirror checks."),
Q("Når bør du gjøre blindsonekontroll?", "ควรเช็คมุมอับเมื่อใด?", "When check blind spot?",
  [("Før feltskifte", "ก่อนเปลี่ยนเลน", "Before lane change"), ("Aldri", "ไม่เคย", "Never"),
   ("Bare på motorvei", "เฉพาะมอเตอร์เวย์", "Motorway only"), ("Kun om natten", "กลางคืน", "Night only")],
  0, "easy", "Feltskifte, forbikjøring og før sving.", "ก่อนเปลี่ยนเลน/แซง/เลี้ยว", "Lane change, overtake, turn."),
Q("Hva forstyrrer oppmerksomheten mest?", "สิ่งรบกวนที่มากที่สุดคือ?", "Biggest attention distractor?",
  [("Bruk av mobiltelefon", "ใช้มือถือ", "Phone use"), ("Radio i bakgrunnen", "วิทยุ", "Background radio"),
   ("Rent frontrute", "กระจกสะอาด", "Clean windshield"), ("Bekvem stol", "เก้าอี้สบาย", "Comfy seat")],
  0, "easy", "Mobilbruk er ledende distraksjon i trafikken.", "มือถือเป็นสาเหตุหลัก", "Phone is top distraction."),
Q("Hva er riktig holdning til risiko?", "ทัศนคติที่ถูกต้องต่อความเสี่ยง?", "Correct attitude to risk?",
  [("Forstå og redusere der mulig", "เข้าใจและลด", "Understand and reduce"), ("Søke risiko", "ตามหาความเสี่ยง", "Seek risk"),
   ("Ignorere", "ไม่สนใจ", "Ignore"), ("Satse på flaks", "หวังโชค", "Rely on luck")],
  0, "easy", "Sikker fører reduserer risiko aktivt.", "ลดความเสี่ยงตลอด", "Actively reduce risk."),
Q("Hva bør du gjøre ved press fra venner om å kjøre fort?", "เพื่อนกดดันให้ขับเร็วควรทำอย่างไร?", "Friend pressure to speed?",
  [("Stå på egne grenser", "ยึดขีดของตัวเอง", "Hold your limits"), ("Gi etter", "ยอม", "Give in"),
   ("Kjøre enda fortere", "ขับเร็วกว่า", "Drive even faster"), ("Ignorere sikkerheten", "ไม่สนใจ", "Ignore safety")],
  0, "medium", "Du er ansvarlig for kjøringen din.", "คุณคือผู้รับผิดชอบ", "You're responsible."),
Q("Hva gjør erfarne sjåfører bedre?", "คนขับที่มีประสบการณ์เก่งเรื่องใด?", "What experienced drivers do better?",
  [("Ser og forutser farer tidligere", "เห็นและคาดการณ์อันตรายได้ไว", "Spot/predict hazards earlier"),
   ("Kjører raskere", "เร็วกว่า", "Drive faster"), ("Bruker mer bensin", "ใช้น้ำมันมาก", "Use more fuel"),
   ("Bruker ikke speil", "ไม่ใช้กระจก", "Skip mirrors")],
  0, "medium", "Erfaring gir bedre persepsjon og valg.", "ประสบการณ์ทำให้เห็นไว", "Experience sharpens perception."),
Q("Hva skjer med reaksjonstiden når du er trøtt?", "ง่วงมีผลต่อเวลาตอบสนองอย่างไร?", "Fatigue and reaction time?",
  [("Reaksjonen blir tregere", "ช้าลง", "Slower"), ("Bedre reaksjon", "เร็วขึ้น", "Faster"),
   ("Ingen endring", "ไม่เปลี่ยน", "No change"), ("Mer presis", "แม่นขึ้น", "More precise")],
  0, "easy", "Trøtthet gir treg reaksjon og dårlig bedømming.", "ง่วงทำให้ช้า", "Fatigue slows reactions."),
Q("Hvordan påvirker alkohol kjøring?", "แอลกอฮอล์มีผลต่อการขับขี่อย่างไร?", "Alcohol on driving?",
  [("Svekker dømmekraft og reaksjon", "ทำให้ตัดสินและตอบสนองแย่ลง", "Impairs judgment & reaction"),
   ("Forbedrer konsentrasjon", "ดีขึ้น", "Improves focus"), ("Ingen effekt", "ไม่มีผล", "No effect"),
   ("Roer nervene trygt", "สงบประสาท", "Safe calm")],
  0, "easy", "Alkohol = farlig i trafikken. 0,2 promille i Norge.", "ไม่ปลอดภัย 0.2‰", "Dangerous. 0.2‰ NO limit."),
Q("Hva kalles fenomenet hvor bilen føles som den glir på vann?", "ปรากฏการณ์รถเหินน้ำเรียกว่าอะไร?", "Car sliding on water film?",
  [("Vannplaning (aquaplaning)", "aquaplaning", "Aquaplaning"), ("Rullegrep", "เกาะกลิ้ง", "Roll-grip"),
   ("Trekkraft", "แรงลาก", "Traction"), ("Sladd", "ลื่น", "Skid")],
  0, "medium", "Vannfilm mellom dekk og asfalt gir tap av grep.", "ฟิล์มน้ำใต้ยาง", "Water film causes grip loss."),
Q("Hva er viktigst ved kjøring i blindsonetrafikanter?", "ผู้ใช้ถนนในจุดอับ ควรทำอย่างไร?", "Users in blind spot?",
  [("Sjekke over skulderen før manøver", "หันมองก่อนเคลื่อน", "Check over shoulder before move"),
   ("Stole på speilene", "เชื่อกระจก", "Trust mirrors only"),
   ("Bruke horn", "บีบแตร", "Use horn"),
   ("Ignorere", "ไม่สนใจ", "Ignore")],
  0, "medium", "Speil dekker ikke alle vinkler — skulderkikk er kritisk.", "ต้องหันมองข้ามไหล่", "Shoulder check is critical."),
Q("Hva er viktig før oppstart av kjøretur?", "ก่อนออกเดินทางควรทำอะไร?", "Before starting a trip?",
  [("Justere speil, sete og belte", "ปรับกระจก/เบาะ/เข็มขัด", "Adjust mirrors/seat/belt"),
   ("Starte rett ut", "ออกทันที", "Just go"),
   ("Høy volum på musikk", "เปิดเพลงดัง", "Loud music"),
   ("Slå av lys", "ปิดไฟ", "Turn off lights")],
  0, "easy", "Korrekt plassering gir bedre sikt og sikkerhet.", "เตรียมตัวก่อนขับ", "Prep before driving."),
Q("Hva viser en god føreradferd?", "พฤติกรรมคนขับที่ดีคือ?", "Good driver behavior?",
  [("Forutsigbar og hensynsfull kjøring", "คาดเดาได้และมีน้ำใจ", "Predictable & considerate"),
   ("Aggressiv kjøring", "ก้าวร้าว", "Aggressive"),
   ("Plutselig bremsing", "เบรกแรงปัจจุบันทันด่วน", "Abrupt braking"),
   ("Ignorere andre", "ไม่สนใจ", "Ignore others")],
  0, "easy", "Forutsigbarhet reduserer ulykker.", "คาดเดาได้ลดอุบัติเหตุ", "Predictability reduces crashes."),
Q("Hvordan påvirker stress kjøringen?", "ความเครียดมีผลต่อการขับขี่?", "Stress on driving?",
  [("Dårligere dømmekraft og tålmodighet", "ตัดสินและอดทนแย่ลง", "Worse judgment & patience"),
   ("Bedre fokus", "โฟกัสดีขึ้น", "Better focus"), ("Ingen effekt", "ไม่มีผล", "No effect"),
   ("Raskere reaksjon", "ไวกว่า", "Faster reactions")],
  0, "medium", "Ta en pause hvis du er stresset.", "พักก่อนถ้าเครียด", "Take a break if stressed."),
Q("Hva er «automatiseret» kjøring?", "การขับอัตโนมัติ หมายถึง?", "'Automated' driving means?",
  [("Handlinger blir innøvd/reflekse", "ทักษะเป็นปฏิกิริยา", "Actions become reflexive"),
   ("Robotbil", "รถอัตโนมัติ", "Robot car"),
   ("Autopilot", "ออโต้ไพลอต", "Autopilot"),
   ("Uten fører", "ไม่มีคนขับ", "No driver")],
  0, "medium", "Erfaring gjør at basisoppgaver automatiseres — frigir fokus.", "ทักษะเคยชินจะเป็นอัตโนมัติ", "Trained skills become automatic."),
Q("Hva gjør du hvis du mister konsentrasjonen?", "เมื่อเสียสมาธิควรทำอย่างไร?", "Losing focus — what do?",
  [("Ta en pause i trygg avkjørsel", "จอดพักที่ปลอดภัย", "Break at a safe pull-off"),
   ("Kjøre fortere", "ขับเร็วขึ้น", "Drive faster"), ("Spise mens du kjører", "กินระหว่างขับ", "Eat while driving"),
   ("Ringe venner", "โทรเพื่อน", "Call friends")],
  0, "easy", "Pause gjenoppretter oppmerksomheten.", "พักเรียกสมาธิ", "Break restores focus."),
Q("Hvilket problem gir sterkt regn for observasjon?", "ฝนแรงมีปัญหาอะไรต่อการมอง?", "Heavy rain issue for observation?",
  [("Redusert sikt og blending av veilys", "ทัศนวิสัยต่ำและแสงรบกวน", "Reduced visibility, glare"),
   ("Bedre sikt", "ดีขึ้น", "Better vis"),
   ("Ingen problem", "ไม่มีปัญหา", "None"),
   ("Kortere bremselengde", "เบรกสั้น", "Shorter braking")],
  0, "easy", "Reduser fart, bruk nærlys og vindusviskere.", "ลด fart, ใช้ไฟต่ำ", "Slow, use low beams."),
Q("Hva bør du unngå å fokusere for mye på?", "ไม่ควรโฟกัสอะไรมากไป?", "Don't over-focus on what?",
  [("En enkelt detalj i synsfeltet", "จุดเดียว", "Single detail"),
   ("Hele trafikkbildet", "ภาพรวม", "Whole picture"),
   ("Langt fram", "ไกลข้างหน้า", "Far ahead"),
   ("Speilene", "กระจก", "Mirrors")],
  0, "medium", "«Tunellsyn» mister informasjon i sidene.", "มองแบบอุโมงค์เสียข้อมูล", "Tunnel vision loses info."),
Q("Hva er fordelen med riktig sittestilling?", "ประโยชน์ของท่านั่งที่ถูก?", "Benefit of correct seating?",
  [("Bedre kontroll og mindre tretthet", "ควบคุมดี ไม่ล้า", "Better control, less fatigue"),
   ("Kortere reise", "สั้นลง", "Shorter trip"),
   ("Lavere forbruk", "ประหยัด", "Lower fuel"),
   ("Raskere radio", "เพลงดัง", "Faster radio")],
  0, "easy", "Rett avstand til ratt og pedaler reduserer tretthet.", "ระยะพวงมาลัย/คันเร่ง", "Right distance to controls."),
Q("Hvorfor er speilet innstilt feil et problem?", "ปรับกระจกผิดเป็นปัญหาอย่างไร?", "Wrongly set mirror problem?",
  [("Større blindsoner", "มุมอับใหญ่ขึ้น", "Larger blind spots"),
   ("Bedre sikt", "ดีขึ้น", "Better view"),
   ("Raskere", "ไวขึ้น", "Faster"),
   ("Sparer plass", "ประหยัด", "Saves space")],
  0, "medium", "Juster sidespeilene til å akkurat se karosseriet.", "ตั้งกระจกให้เห็นขอบตัวรถเล็กน้อย", "Set mirrors to barely see body."),
Q("Hva er den typiske reaksjonstiden for en oppmerksom sjåfør?", "เวลาตอบสนองของคนขับที่ตื่นตัวเป็นเท่าไร?", "Alert driver's typical reaction time?",
  [("Omtrent 1 sekund", "ประมาณ 1 วินาที", "About 1 second"),
   ("0,1 sekund", "0.1 วินาที", "0.1 sec"),
   ("5 sekunder", "5 วินาที", "5 sec"),
   ("10 sekunder", "10 วินาที", "10 sec")],
  0, "medium", "~1 s reaksjon pluss bremse- og stopplengde.", "~1 วินาที", "~1 s then braking."),
Q("Hva er «risikoforståelse»?", "\"ความเข้าใจความเสี่ยง\" คืออะไร?", "What is 'risk understanding'?",
  [("Se farer og vurdere konsekvenser", "มองอันตรายและประเมินผล", "See hazards, judge outcome"),
   ("Kjøre uten regler", "ขับไม่มีกฎ", "Drive without rules"),
   ("Bare lover", "เฉพาะกฎหมาย", "Just laws"),
   ("Kun fartstopp", "หยุดเร็ว", "Only stopping")],
  0, "medium", "Grunnsten for trygg kjøring.", "รากฐานความปลอดภัย", "Foundation of safe driving."),
Q("Hvor langt fram bør du se på motorvei?", "บนมอเตอร์เวย์ควรมองไกลเท่าไร?", "How far ahead on motorway?",
  [("Minst 12–15 sekunder fram", "อย่างน้อย 12–15 วินาที", "At least 12–15 s ahead"),
   ("2–3 sekunder", "2–3 วินาที", "2–3 s"),
   ("Bare bilen foran", "แค่รถคันหน้า", "Only car ahead"),
   ("Ingen forskjell", "เท่าไหร่ก็ได้", "Doesn't matter")],
  0, "medium", "Høy fart = lengre framsyn.", "fart สูงต้องมองไกล", "High speed = see far."),
Q("Hva er «tunnelsyn» et symptom på?", "\"มุมมองอุโมงค์\" เป็นอาการของอะไร?", "Tunnel vision is a symptom of?",
  [("Stress eller høy fart", "เครียดหรือ fart สูง", "Stress or high speed"),
   ("Godt lys", "แสงดี", "Good light"),
   ("Rent dekk", "ยางสะอาด", "Clean tire"),
   ("Ro og avslapping", "ผ่อนคลาย", "Relaxation")],
  0, "medium", "Reduser fart og pust rolig.", "ลด fart หายใจลึก", "Slow down, breathe."),
Q("Hva er risikoen ved høy musikk i bilen?", "ฟังเพลงดังในรถเสี่ยงอะไร?", "Risk of loud music in car?",
  [("Dårligere varsling og konsentrasjon", "ได้ยินและโฟกัสน้อยลง", "Worse hearing & focus"),
   ("Bedre konsentrasjon", "ดีขึ้น", "Better focus"),
   ("Sparer drivstoff", "ประหยัด", "Fuel saving"),
   ("Kortere reisetid", "ไปไว", "Faster trip")],
  0, "easy", "Senk volumet så du hører sirener og andre varsler.", "ลดเสียงเพื่อให้ได้ยินไซเรน", "Lower volume for sirens."),
Q("Hva hjelper best mot trøtthet på lang tur?", "อะไรช่วยแก้ง่วงระยะไกล?", "Best anti-fatigue on long trips?",
  [("Pauser hver 2. time", "พักทุก 2 ชม.", "Break every 2 h"),
   ("Mer kaffe", "กาแฟเพิ่ม", "More coffee"),
   ("Åpne vinduet", "เปิดหน้าต่าง", "Open window"),
   ("Løpende", "เร่งต่อ", "Keep pushing")],
  0, "easy", "Regelmessige pauser er mest effektivt.", "พักสม่ำเสมอ", "Regular breaks work best."),
Q("Hva er selvinnsikt i kjøringen?", "การรู้จักตนเองในการขับขี่?", "Self-awareness in driving?",
  [("Kjenne egne styrker og svakheter", "รู้จุดเด่น/จุดอ่อน", "Know strengths/weaknesses"),
   ("Aldri innrømme feil", "ไม่ยอมผิด", "Never admit fault"),
   ("Stole på flaks", "หวังโชค", "Rely on luck"),
   ("Kopiere andre", "เลียนแบบ", "Copy others")],
  0, "medium", "Hjelper deg velge trygge beslutninger.", "ช่วยตัดสินใจปลอดภัย", "Helps safe decisions."),
Q("Hva gjør man når man ser en myk trafikant tidlig?", "เห็นคนเดิน/จักรยานไวๆ ควรทำอย่างไร?", "Early spot of vulnerable user?",
  [("Reduser fart og vær klar", "ลด fart พร้อมหยุด", "Reduce speed, ready"),
   ("Holde farten", "คงที่", "Keep speed"),
   ("Tute", "บีบแตร", "Honk"),
   ("Ignorere", "ไม่สนใจ", "Ignore")],
  0, "easy", "Gi deg selv tid og rom til å reagere.", "ให้เวลาตอบสนอง", "Give yourself time to react."),
Q("Hva bør nye sjåfører være mest obs på?", "คนขับใหม่ควรระวังอะไรมากที่สุด?", "New drivers — watch most for?",
  [("Manglende erfaring i avanserte situasjoner", "ขาดประสบการณ์สถานการณ์ยาก", "Inexperience in hard situations"),
   ("Drivstoffpris", "ราคาน้ำมัน", "Fuel price"),
   ("Radioreklame", "โฆษณาวิทยุ", "Ads"),
   ("Skiltdesign", "ดีไซน์ป้าย", "Sign design")],
  0, "medium", "Unge/nye sjåfører har høyest ulykkesrisiko.", "เสี่ยงที่สุดในปีแรกๆ", "Highest risk early years."),
Q("Hvilke tre forhold utgjør risiko i trafikken?", "สามปัจจัยความเสี่ยงในจราจรคือ?", "Three risk factors in traffic?",
  [("Fører, kjøretøy, veg/forhold", "คน รถ ถนน", "Driver, vehicle, road"),
   ("Bare føreren", "เฉพาะคน", "Only driver"),
   ("Bare bilen", "เฉพาะรถ", "Only car"),
   ("Bare været", "เฉพาะอากาศ", "Only weather")],
  0, "medium", "Alle tre må vurderes sammen.", "ต้องมองทั้งสาม", "All three matter."),
Q("Hva vil sikre god oversikt i kryss?", "สร้างภาพรวมที่ดีในแยกได้อย่างไร?", "Good overview at junction?",
  [("Senke fart og se begge retninger", "ลด fart มองทั้งสองทาง", "Slow, look both ways"),
   ("Holde farten", "คงที่", "Keep speed"),
   ("Se bare til høyre", "มองแต่ขวา", "Only right"),
   ("Bruke kart", "ดูแผนที่", "Check map")],
  0, "easy", "Kryss krever aktiv observasjon.", "แยกต้องมองจริงจัง", "Junctions need active look."),
Q("Hva betyr «å være aktpågivende»?", "\"ระมัดระวัง\" หมายถึง?", "What does 'attentive' mean?",
  [("Å være oppmerksom på farer", "รู้ทันอันตราย", "Aware of hazards"),
   ("Å kjøre fort", "ขับเร็ว", "Drive fast"),
   ("Å snakke mye", "พูดเยอะ", "Talk a lot"),
   ("Å sove", "นอน", "Sleep")],
  0, "easy", "Pliktig krav i vegtrafikkloven.", "เป็นหน้าที่ตามกฎหมาย", "Legal duty."),
Q("Hva er konsekvens av \"fort og gæli\"-holdning?", "ทัศนคติ \"รีบและสะเพร่า\" ส่งผลอย่างไร?", "'Fast and sloppy' attitude result?",
  [("Økt ulykkesrisiko", "เสี่ยงสูงขึ้น", "Higher crash risk"),
   ("Bedre kjøring", "ดีขึ้น", "Better driving"),
   ("Lavere forbruk", "ประหยัด", "Less fuel"),
   ("Mer respekt", "ได้ใจคน", "More respect")],
  0, "easy", "Hastverk + unøyaktighet = farlig kombinasjon.", "รีบ+ผิดพลาด = อันตราย", "Rush + errors = danger."),
Q("Hva er det første tegnet på tretthet?", "สัญญาณเหนื่อยล้าอันแรกคือ?", "First sign of fatigue?",
  [("Gjesping og seige bevegelser", "หาว ตัวหนัก", "Yawning & sluggishness"),
   ("Skarp fokus", "โฟกัสจัด", "Sharp focus"),
   ("Aktiv samtale", "คุยเยอะ", "Chatty"),
   ("Høy energi", "พลังงานสูง", "High energy")],
  0, "easy", "Kjenn igjen tidlige tegn og ta pause.", "รู้ตัวและพัก", "Recognize and rest."),
Q("Hvordan jobber en defensiv fører?", "ผู้ขับแบบป้องกันทำอย่างไร?", "How does a defensive driver drive?",
  [("Forutser feil fra andre", "คาดว่าคนอื่นอาจพลาด", "Expects others' errors"),
   ("Stoler på at alle kjører rett", "เชื่อทุกคนขับถูก", "Trusts everyone is correct"),
   ("Ignorerer speil", "ไม่ดูกระจก", "Skips mirrors"),
   ("Kjører fort", "เร็ว", "Fast")],
  0, "medium", "Legg inn sikkerhetsmargin.", "เผื่อระยะปลอดภัย", "Leave safety margin."),
Q("Hva kan hindre god sikt i bilen?", "อะไรบดบังทัศนวิสัยในรถได้?", "What blocks in-car visibility?",
  [("Store gjenstander på dashbord", "ของใหญ่บนแดชบอร์ด", "Large items on dash"),
   ("Rent glass", "กระจกสะอาด", "Clean glass"),
   ("Riktige speil", "กระจกดี", "Proper mirrors"),
   ("Nok lys", "แสงพอ", "Enough light")],
  0, "easy", "Hold dashbordet ryddig og rutene rene.", "เก็บแดชให้โล่ง", "Keep dash clear."),
Q("Hvorfor er risikoen størst for unge menn?", "ทำไมผู้ชายอายุน้อยเสี่ยงสุด?", "Why risk highest for young men?",
  [("Mindre erfaring + mer risikotaking", "ประสบการณ์น้อย+เสี่ยงมาก", "Less exp + more risk-taking"),
   ("Bedre biler", "รถดีกว่า", "Better cars"),
   ("Flere regler", "กฎมากกว่า", "More rules"),
   ("Mer refleksiv", "ไวกว่า", "More reflexive")],
  0, "hard", "Kombinasjon av ferskhet og risikovillighet gir høyest statistikk.", "ผสมขาดประสบการณ์+ชอบเสี่ยง", "Combo of inexperience + risk appetite."),
Q("Hva er beste tiltak for å bli en trygg sjåfør?", "วิธีดีสุดในการเป็นคนขับที่ปลอดภัย?", "Best way to become safer driver?",
  [("Øve mye i ulike forhold", "ฝึกหลายสภาพ", "Practice in varied conditions"),
   ("Kjøre bare i sol", "ขับตอนแดด", "Drive only in sun"),
   ("Stort dekk", "ยางใหญ่", "Big tires"),
   ("Ny bil", "รถใหม่", "New car")],
  0, "medium", "Øvelse + refleksjon over egne feil.", "ฝึก+ทบทวน", "Practice + self-reflect."),
Q("Hva er \"riktig\" bruk av ADAS (kollisjonsvarsling/ACC)?", "ใช้ ADAS อย่างถูกต้องคือ?", "Correct use of ADAS?",
  [("Som støtte — ikke som erstatning", "ช่วยเสริม ไม่แทนคน", "As aid, not replacement"),
   ("Erstatte oppmerksomhet", "แทนการมอง", "Replaces attention"),
   ("Slippe rattet", "ปล่อยพวงมาลัย", "Let go of wheel"),
   ("Sove", "นอน", "Sleep")],
  0, "medium", "Systemene kan feile — du er alltid sjåføren.", "ระบบอาจพลาด คุณคือคนขับ", "Systems can fail; you drive."),
Q("Hva er konsekvensen av kjøring uten belte?", "ขับไม่คาดเข็มขัดผลคืออะไร?", "Driving without seatbelt?",
  [("Vesentlig større skaderisiko", "เสี่ยงบาดเจ็บมาก", "Much higher injury risk"),
   ("Lavere forbruk", "ประหยัด", "Less fuel"),
   ("Bedre sikt", "มองดีขึ้น", "Better view"),
   ("Ingen forskjell", "ไม่ต่าง", "No difference")],
  0, "easy", "Belte reduserer dødsrisikoen betydelig.", "เข็มขัดลดเสี่ยงตายมาก", "Belts cut fatality risk."),
Q("Hva er en viktig kilde til feilhandlinger?", "อะไรเป็นสาเหตุของการทำผิด?", "Key source of driver errors?",
  [("Mangelfull observasjon", "มองไม่เห็น", "Poor observation"),
   ("For mange speil", "กระจกมากไป", "Too many mirrors"),
   ("For mange lys", "ไฟเยอะ", "Too many lights"),
   ("For lite gass", "เหยียบน้อย", "Too little throttle")],
  0, "medium", "Se → forstå → velg → handle.", "มอง→เข้าใจ→เลือก→ทำ", "See → grasp → choose → act."),
Q("Hvorfor er det farlig å kjøre etter tidsfrist?", "ทำไมขับแบบเร่งเวลาจึงอันตราย?", "Why dangerous to drive on tight deadline?",
  [("Press fører til risikable valg", "กดดันนำไปสู่การเสี่ยง", "Pressure → risky choices"),
   ("Du kommer tidligere", "ถึงก่อน", "Arrive earlier"),
   ("Bedre kjøring", "ขับดีขึ้น", "Better drive"),
   ("Mindre stress", "เครียดน้อย", "Less stress")],
  0, "medium", "Plan god tid, reduser risiko.", "วางแผนล่วงหน้า", "Plan ahead, reduce risk."),
Q("Hva er «sovende» risiko?", "\"ความเสี่ยงแฝง\" คืออะไร?", "What is 'hidden/latent' risk?",
  [("Fare som ikke er synlig ennå", "อันตรายยังไม่ปรากฏ", "Danger not yet visible"),
   ("Fare i mørket", "อันตรายในมืด", "Dark danger"),
   ("Fare i snø", "อันตรายในหิมะ", "Snow danger"),
   ("Fare i regn", "อันตรายในฝน", "Rain danger")],
  0, "hard", "F.eks. barn bak parkerte biler, vilt i skog.", "เช่น เด็กหลังรถจอด/สัตว์ในป่า", "E.g., kids behind cars, wildlife."),
Q("Når er det smart å avvike fra fartsgrensen (under)?", "ขับช้ากว่าป้ายเมื่อใดที่สมควร?", "When slower than limit is smart?",
  [("Når forholdene krever det", "เมื่อสภาพต้องการ", "When conditions require"),
   ("Aldri", "ไม่เคย", "Never"),
   ("Alltid", "เสมอ", "Always"),
   ("På motorvei", "มอเตอร์เวย์", "On motorway")],
  0, "medium", "Fartsgrense er maks — du velger trygg fart.", "ป้ายคือสูงสุด", "Limit is a max."),
]

print(f"Batch 1 count: {len(DATA)}")

# ===== BATCH 2: SPEED & DISTANCE (45) =====
B2 = [
Q("Hva er fartsgrensen i tettbygd strøk?", "ในเขตเมืองความเร็วสูงสุดคือ?", "Urban area speed limit?",
  [("50 km/t", "50", "50"), ("30 km/t", "30", "30"), ("60 km/t", "60", "60"), ("80 km/t", "80", "80")],
  0, "easy", "Generell grense i tettbygd strøk er 50 km/t.", "ทั่วไป 50 กม./ชม.", "General urban 50 km/h."),
Q("Hva er generell fartsgrense utenfor tettbygd strøk?", "นอกเขตเมืองทั่วไปคือ?", "Default rural limit?",
  [("80 km/t", "80", "80"), ("60 km/t", "60", "60"), ("100 km/t", "100", "100"), ("50 km/t", "50", "50")],
  0, "easy", "Utenfor tettbygd: 80 km/t som standard.", "นอกเมือง 80", "Rural default 80."),
Q("Hva er maks tillatt fart på motorvei i Norge?", "บนมอเตอร์เวย์ในนอร์เวย์สูงสุด?", "Max speed on NO motorway?",
  [("110 km/t", "110", "110"), ("130 km/t", "130", "130"), ("100 km/t", "100", "100"), ("90 km/t", "90", "90")],
  0, "easy", "Opp til 110 km/t på utvalgte motorveier.", "ไม่เกิน 110", "Up to 110."),
Q("Hva er fartsgrensen i gatetun?", "\"gatetun\" ความเร็วเท่าไร?", "Speed in residential courtyard (gatetun)?",
  [("Gangfart (ca 6 km/t)", "เดินเท้า ~6", "Walking pace ~6"),
   ("30 km/t", "30", "30"), ("50 km/t", "50", "50"), ("20 km/t", "20", "20")],
  0, "medium", "I gatetun: gangfart og vikeplikt for alle gående.", "เดินเท้า+ให้ทาง", "Walking pace + yield."),
Q("Hva doblet fart gjør med bremselengden?", "เพิ่ม fart 2 เท่าระยะเบรกเป็น?", "Doubling speed → braking distance?",
  [("4× lengre", "×4", "4×"), ("2× lengre", "×2", "2×"), ("3× lengre", "×3", "3×"), ("Uendret", "เท่าเดิม", "Same")],
  0, "medium", "Bremselengde ∝ fart².", "เป็นสัดส่วนกับกำลังสอง", "∝ speed²."),
Q("Hvor langt kjører du på 1 sekund i 90 km/t?", "ที่ 90 km/h ใน 1 วินาที?", "Distance in 1 s at 90 km/h?",
  [("25 m", "25", "25"), ("10 m", "10", "10"), ("50 m", "50", "50"), ("15 m", "15", "15")],
  0, "medium", "90/3,6 ≈ 25 m/s.", "90/3.6 ≈ 25", "90/3.6 ≈ 25 m."),
Q("Hva er 3-sekunders-regelen?", "กฎ 3 วินาทีคืออะไร?", "3-second rule?",
  [("Minimum avstand til bilen foran", "เว้นระยะ 3 วิ", "Min gap to car ahead"),
   ("Tid til å svinge", "เวลาเลี้ยว", "Time to turn"),
   ("Tid til å blinke", "เวลาเปิดไฟ", "Time to signal"),
   ("Tid til å stoppe", "เวลาหยุด", "Time to stop")],
  0, "easy", "Sikkerhetsavstand i tørt vær.", "ระยะปลอดภัย", "Safety gap in dry."),
Q("Hva bør sikkerhetsavstand være ved våt vei?", "ถนนเปียกระยะห่างเป็นเท่าไร?", "Safety gap on wet road?",
  [("Minst 4-5 sekunder", "อย่างน้อย 4-5 วิ", "At least 4-5 s"),
   ("1 sekund", "1 วิ", "1 s"),
   ("2 sekunder", "2 วิ", "2 s"),
   ("Samme som tørt", "เท่าแห้ง", "Same as dry")],
  0, "medium", "Våt vei dobler bremselengden omtrent.", "เปียก = ระยะเบรกยาวขึ้น", "Wet ~2× braking distance."),
Q("Hva bør sikkerhetsavstand være på is?", "บนน้ำแข็งระยะห่าง?", "Gap on ice?",
  [("8+ sekunder", "8+ วิ", "8+ s"),
   ("3 sekunder", "3 วิ", "3 s"),
   ("1 sekund", "1 วิ", "1 s"),
   ("Uendret", "เท่าเดิม", "Same")],
  0, "medium", "Is kan gi 4-10× bremselengde.", "น้ำแข็งเบรกยากมาก", "Ice dramatically increases braking."),
Q("Hva er din stopplengde (reaksjon + brems) ved 90 km/t tørt vær?", "ที่ 90 km/h แห้งระยะหยุดรวม?", "Total stop at 90 km/h dry?",
  [("~70 m", "~70", "~70"), ("~20 m", "~20", "~20"), ("~150 m", "~150", "~150"), ("~10 m", "~10", "~10")],
  0, "hard", "Reaksjon ~25 m + brems ~45 m ≈ 70 m.", "ประมาณ 70 ม.", "~70 m."),
Q("Hvorfor gir høy fart lengre bremselengde?", "ทำไม fart สูงเบรกยาวขึ้น?", "Why high speed → longer braking?",
  [("Kinetisk energi øker med fart²", "พลังงานจลน์ ∝ ความเร็ว²", "KE ∝ speed²"),
   ("Dekk blir slitt", "ยางสึก", "Tires wear"),
   ("Bremser blir kalde", "เบรกเย็น", "Brakes cool"),
   ("Mer luft", "อากาศเยอะ", "More air")],
  0, "medium", "Derfor doblet fart = 4× bremselengde.", "จึง ×4 เมื่อ ×2", "Hence 4× at 2× speed."),
Q("Hva er reaksjonslengden ved 50 km/t (1 s)?", "reaction ที่ 50 km/h (1 วิ) คือ?", "Reaction distance at 50 km/h (1 s)?",
  [("~14 m", "~14", "~14"), ("~5 m", "~5", "~5"), ("~30 m", "~30", "~30"), ("~50 m", "~50", "~50")],
  0, "medium", "50/3,6 ≈ 14 m/s.", "50/3.6≈14", "50/3.6 ≈ 14 m."),
Q("Hva er tillatt promille for vanlig førerkort i Norge?", "แอลกอฮอล์ในเลือดสูงสุดในนอร์เวย์?", "BAC limit in Norway?",
  [("0,2 promille", "0.2‰", "0.2‰"), ("0,5 promille", "0.5‰", "0.5‰"),
   ("0,8 promille", "0.8‰", "0.8‰"), ("0,0 promille", "0.0‰", "0.0‰")],
  0, "easy", "Streng grense for å avskrekke kjøring i påvirket tilstand.", "เข้มงวด 0.2", "Strict 0.2."),
Q("Når kan du lovlig kjøre fortere enn skiltet grense?", "จะขับเกินป้ายได้เมื่อใด?", "When can you legally exceed limit?",
  [("Aldri (med unntak av utrykning)", "ไม่ได้ (ยกเว้นฉุกเฉิน)", "Never (except emergency vehicles)"),
   ("Når vei er tom", "ถนนโล่ง", "Empty road"),
   ("Om natten", "กลางคืน", "Night"),
   ("I regn", "ฝน", "Rain")],
  0, "easy", "Fartsgrense = lovfestet maks.", "ป้ายเป็นกฎหมาย", "Limit = law."),
Q("Hva bør du gjøre ved sikt under 50 m?", "ทัศนวิสัยต่ำกว่า 50 ม.?", "Visibility under 50 m?",
  [("Redusere fart sterkt og øke avstand", "ลด fart มาก, เว้นระยะ", "Slow hard, increase gap"),
   ("Holde 80", "คง 80", "Keep 80"),
   ("Tenne fjernlys", "ไฟสูง", "High beam"),
   ("Ignorere", "ไม่สนใจ", "Ignore")],
  0, "medium", "Sikt bestemmer maks fart.", "ทัศนวิสัยกำหนด fart", "Visibility caps speed."),
Q("Hvor lang luke må du ha foran deg før du kan gå inn i forbikjøring?", "ก่อนแซงต้องเผื่อระยะข้างหน้าเท่าไร?", "Forward gap before overtaking?",
  [("Nok til å fullføre trygt + margin", "พอให้แซงเสร็จ + เผื่อ", "Enough to finish + margin"),
   ("Akkurat nok", "พอดี", "Just enough"),
   ("Ingen", "ไม่ต้อง", "None"),
   ("Kun fra venstre", "จากซ้าย", "From left only")],
  0, "medium", "Du må rekke å komme trygt tilbake før møtende.", "ต้องกลับเลนได้ทัน", "Must return before oncoming."),
Q("Hva er maks fart med tilhenger i Norge (uten bremser)?", "ลากพ่วงไม่มีเบรกสูงสุด?", "Trailer without brakes — max speed?",
  [("60 km/t", "60", "60"), ("80 km/t", "80", "80"), ("90 km/t", "90", "90"), ("100 km/t", "100", "100")],
  0, "hard", "Tilhenger uten brems: 60 km/t maks.", "ไม่มีเบรก 60", "No-brake trailer: 60."),
Q("Hva er maks fart med tilhenger (med bremser)?", "ลากพ่วงมีเบรกสูงสุด?", "Trailer with brakes — max?",
  [("80 km/t", "80", "80"), ("60 km/t", "60", "60"), ("100 km/t", "100", "100"), ("110 km/t", "110", "110")],
  0, "hard", "Tilhenger med brems: normalt 80 km/t.", "มีเบรก 80", "Braked trailer: 80."),
Q("Hva er fartsgrense forbi skole (som regel)?", "ใกล้โรงเรียนมักเท่าไร?", "Speed near schools?",
  [("Ofte 30–40 km/t (se skilt)", "มัก 30-40", "Often 30-40"),
   ("Alltid 80", "80", "Always 80"),
   ("Alltid 50", "50", "50"),
   ("Alltid 10", "10", "10")],
  0, "medium", "Variabelt — les skilt og vær ekstra oppmerksom.", "ดูป้าย", "Read signs."),
Q("Hva er stopplengde = reaksjon + bremse?", "ระยะหยุดรวมคือ?", "Stop distance = ?",
  [("Reaksjonslengde + bremselengde", "ระยะคิด + ระยะเบรก", "Reaction + braking"),
   ("Bare bremsing", "เฉพาะเบรก", "Only braking"),
   ("Bare reaksjon", "เฉพาะคิด", "Only reaction"),
   ("Fart ganget med 2", "×2", "× 2")],
  0, "easy", "Samlet tid fra du ser farer til bilen står.", "เวลาทั้งหมดจนหยุด", "Total time seeing to stopping."),
Q("Hvordan påvirker kald temperatur bremsene?", "อากาศเย็นมีผลต่อเบรกอย่างไร?", "Cold and brakes?",
  [("Kan gi svakere grep initialt", "เกาะน้อยลงตอนเริ่ม", "Reduced grip initially"),
   ("Bedre bremser", "ดีขึ้น", "Better"),
   ("Ingen endring", "ไม่เปลี่ยน", "Same"),
   ("Raskere tørking", "แห้งไว", "Dries faster")],
  0, "medium", "Kalde dekk og våt asfalt = lengre bremselengde.", "ยางเย็นเกาะน้อย", "Cold tires grip less."),
Q("Hva heter området bak «myk» stopplys?", "หลังไฟท้ายของคันหน้าเรียกว่า?", "Zone right behind car ahead?",
  [("Sikkerhetsavstand", "ระยะปลอดภัย", "Safety gap"),
   ("Bruksavstand", "ใช้งาน", "Use gap"),
   ("Manøvrering", "Maneuver", "Maneuver"),
   ("Fartshaster", "fast zone", "Fast zone")],
  0, "easy", "Sikkerhetsavstand bør alltid være overholdt.", "ต้องเว้นระยะ", "Always keep gap."),
Q("Hva gjør du hvis bilen bak kjører altfor tett?", "คันหลังจี้มากควรทำอย่างไร?", "Tailgater behind you?",
  [("Senk fart gradvis og la dem passere", "ลด fart และให้เขาแซง", "Ease speed, let them pass"),
   ("Brems hardt", "เบรกแรง", "Brake hard"),
   ("Øke fart", "เพิ่มเร็ว", "Increase"),
   ("Flipp av", "ขับแปลก", "Weird moves")],
  0, "medium", "Unngå eskalering — gi dem trygt rom.", "หลีกเลี่ยง", "Avoid escalation."),
Q("Hvorfor er høy fart farlig i tunnel?", "เร็วในอุโมงค์ทำไมอันตราย?", "Why speed dangerous in tunnel?",
  [("Liten plass, ingen rømningsvei", "ที่น้อย หนีไม่ได้", "Tight, no escape"),
   ("Bedre lys", "แสงดี", "Better light"),
   ("Jevnere asfalt", "เรียบกว่า", "Smoother"),
   ("Mindre vind", "ลมน้อย", "Less wind")],
  0, "medium", "Ulykker i tunnel eskalerer raskt.", "อุบัติเหตุในอุโมงค์รุนแรงไว", "Tunnel crashes escalate fast."),
Q("Hva gjør rekkefølge av reaksjon vs. brems?", "ลำดับคิดและเบรกเป็นอย่างไร?", "Reaction vs braking order?",
  [("Reaksjon først, deretter brems", "คิดก่อน แล้วเบรก", "Reaction first, then brake"),
   ("Brems først", "เบรกก่อน", "Brake first"),
   ("Samtidig", "พร้อมกัน", "Simultaneous"),
   ("Aldri", "ไม่เคย", "Never")],
  0, "easy", "Hjernen må først oppfatte og bestemme.", "สมองต้องรับรู้ก่อน", "Brain must perceive first."),
Q("Hva bør du gjøre ved nedoverbakke?", "ลงเขาควรทำอย่างไร?", "Downhill — what to do?",
  [("Bruke motorbrems (lavere gir)", "ใช้เกียร์ต่ำ", "Use engine braking"),
   ("Fri gir", "เกียร์ว่าง", "Neutral"),
   ("Øke fart", "เร่ง", "Increase speed"),
   ("Bare bremsepedal", "เบรกเท้าอย่างเดียว", "Only pedal")],
  0, "easy", "Motorbrems beskytter bremsene.", "กันเบรกไหม้", "Protect brakes."),
Q("Når du øker farten fra 50 til 70 km/t, hva skjer med stopplengden?", "50→70 ระยะหยุด?", "50→70 stop distance?",
  [("Nesten dobles", "เกือบสองเท่า", "Almost doubles"),
   ("Uendret", "เท่าเดิม", "Same"),
   ("Halveres", "ครึ่งหนึ่ง", "Halves"),
   ("Øker 10%", "10%", "+10%")],
  0, "hard", "Stor forskjell: kinetisk energi øker kraftig.", "พลังงานจลน์เพิ่มมาก", "KE rises sharply."),
Q("Hva betyr «foregriping» i trafikken?", "\"การคาดการณ์\" คือ?", "'Anticipation' in traffic?",
  [("Forutse hva som kan skje", "คาดการณ์สถานการณ์", "Foresee what can happen"),
   ("Se bakover", "มองหลัง", "Look back"),
   ("Stoppe", "หยุด", "Stop"),
   ("Bremse", "เบรก", "Brake")],
  0, "medium", "Bruker fart og plassering til å forberede deg.", "ใช้ fart/ตำแหน่งเตรียม", "Use speed/position to prep."),
Q("Hva er «fart etter forholdene»?", "\"fart ตามสภาพ\" คือ?", "'Speed for conditions'?",
  [("Lavere enn grensen når situasjonen krever", "ต่ำกว่าป้ายเมื่อจำเป็น", "Lower than limit when needed"),
   ("Alltid grensen", "ป้ายเสมอ", "Always at limit"),
   ("Alltid over", "เกินเสมอ", "Always above"),
   ("Aldri under", "ห้ามต่ำกว่า", "Never below")],
  0, "easy", "Tilpass fart til vei/vær/trafikk.", "ปรับตามสภาพ", "Adapt to conditions."),
Q("Hva er «luke» ved forbikjøring?", "\"ช่องว่าง\" ในการแซงคือ?", "Gap in overtaking?",
  [("Plass foran og bak i feltet du går til", "ที่ว่างหน้าและหลังในเลนที่ไป", "Space ahead & behind in target lane"),
   ("Bare plass foran", "เฉพาะหน้า", "Only ahead"),
   ("Bare plass bak", "เฉพาะหลัง", "Only behind"),
   ("Ingen", "ไม่มี", "None")],
  0, "medium", "Du trenger rom både foran og bak.", "ต้องเว้นสองฝั่ง", "Need space both sides."),
Q("Hva er \"møteklokke\" / \"møtekontroll\"?", "การประเมินสวนทางคือ?", "Assessing oncoming — what's 'meeting' check?",
  [("Vurdere om møtende er trygt forbi", "ประเมินสวนทางให้ปลอดภัย", "Judge oncoming safely"),
   ("Klokkeslett", "เวลา", "Clock time"),
   ("Lukte vedstempel", "กลิ่น", "Smell"),
   ("Lydsjekk", "เสียง", "Sound check")],
  0, "hard", "Før forbikjøring: sjekk møtende kontinuerlig.", "ดูรถสวนต่อเนื่อง", "Keep watching oncoming."),
Q("Hva skjer med styringen ved vannplaning?", "เหินน้ำทำให้พวงมาลัยเป็นอย่างไร?", "Aquaplaning steering?",
  [("Styringen blir lett/uten respons", "เบา ไม่ตอบสนอง", "Goes light/unresponsive"),
   ("Blir tungt", "หนัก", "Gets heavy"),
   ("Normal", "ปกติ", "Normal"),
   ("Roterer", "หมุน", "Rotates")],
  0, "medium", "Hold rett og slipp gass — ikke brems hardt.", "ตรงและผ่อน", "Keep straight, ease off."),
Q("Hva bør dekkmønster minst være?", "ดอกยางขั้นต่ำคือ?", "Minimum tread depth?",
  [("1,6 mm (3 mm vinter anbefalt)", "1.6 มม. (3 มม. หนาว)", "1.6 mm (3 mm winter rec.)"),
   ("0,5 mm", "0.5", "0.5"),
   ("5 mm", "5", "5"),
   ("10 mm", "10", "10")],
  0, "medium", "Under 1,6 mm er ulovlig.", "ต่ำกว่า 1.6 ผิดกฎหมาย", "Below 1.6 is illegal."),
Q("Hvorfor er 150 km/t i fartsgrense 80-sone farlig?", "150 ในเขต 80 อันตรายเพราะอะไร?", "150 in 80 zone — why risky?",
  [("Enorm stoppelengde + ulovlig", "หยุดยาก+ผิดกฎหมาย", "Huge stopping + illegal"),
   ("Ikke farlig", "ไม่อันตราย", "Not risky"),
   ("Sparer tid", "ประหยัดเวลา", "Saves time"),
   ("Bedre grep", "เกาะดี", "Better grip")],
  0, "easy", "Du kan miste førerkortet direkte ved så grov overtredelse.", "ยึดใบขับได้ทันที", "Instant license suspension possible."),
Q("Hva er sikker fart på glatt vei?", "ถนนลื่น fart ปลอดภัย?", "Safe speed on slippery road?",
  [("Mye lavere enn skiltgrense", "ต่ำกว่าป้ายมาก", "Well below limit"),
   ("Full fart", "เต็มที่", "Full"),
   ("Over grensen", "เกินป้าย", "Above limit"),
   ("Ikke bry deg", "ไม่สน", "Don't care")],
  0, "easy", "Grepet bestemmer trygg fart.", "การเกาะกำหนด", "Grip decides."),
Q("Hva er karakter for «dødbalanse» fart?", "\"สมดุลความตาย\" ของ fart คือ?", "Speed 'death balance'?",
  [("Overgang mellom skadegrad lav og høy (~40 km/t støt)", "~40 ช่วงวิกฤต", "~40 km/h critical"),
   ("Maks bilfart", "fart สูงสุด", "Max speed"),
   ("Tomgang", "เดินเบา", "Idle"),
   ("Tomt batteri", "แบตหมด", "Dead battery")],
  0, "hard", "Ved støtfart > 40 km/t øker dødsrisikoen raskt.", "เกิน 40 เสี่ยงตายมาก", "Above 40 km/h impact = death risk spikes."),
Q("Hva betyr «stopp på sikt»?", "\"หยุดตามทัศนวิสัย\" คือ?", "'Stop within sight'?",
  [("Kjør så du kan stoppe innen du ser vei", "ขับให้หยุดทันภายในที่เห็น", "Drive so you can stop within visible distance"),
   ("Se langt fram", "มองไกล", "See far"),
   ("Se tilbake", "มองหลัง", "See back"),
   ("Ignorere sikt", "ไม่สน", "Ignore")],
  0, "medium", "Fart bør alltid kunne stoppe på oversiktlig del.", "fart ต้องหยุดได้ในระยะที่เห็น", "Speed must stop in what you see."),
Q("Hva gjør du hvis du ser \"rødt lys\" på fartsskilt (varianten med hastighetskontroll)?", "ด่านตรวจความเร็วเห็นไฟแดง?", "Speed camera red flash?",
  [("Forvent brev + bot", "คาดได้รับใบสั่ง", "Expect a ticket"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Snu", "กลับรถ", "U-turn"),
   ("Hoppe", "กระโดด", "Jump")],
  0, "medium", "Respekter grenser for å unngå bot.", "เคารพความเร็ว", "Respect limits."),
Q("Hva bør du unngå ved forbikjøring?", "แซงห้ามทำอะไร?", "Avoid when overtaking?",
  [("Foran uoversiktlig bakketopp/sving/kryss", "เนิน/โค้ง/แยกมองไม่เห็น", "Before blind crests/curves/junctions"),
   ("Rett strekning", "ทางตรง", "Straight road"),
   ("God sikt", "มองชัด", "Good sight"),
   ("Tørt vær", "อากาศแห้ง", "Dry")],
  0, "medium", "Aldri med redusert sikt.", "อย่าแซงเมื่อมองไม่เห็น", "Never with reduced visibility."),
Q("Hva skjer dersom du kjører over fartsgrensen i 30-sone?", "ขับเกินในเขต 30?", "Over limit in 30-zone?",
  [("Høy bot — barn i området", "ค่าปรับสูง เขตเด็ก", "Heavy fine — kids zone"),
   ("Ingen reaksjon", "ไม่มีอะไร", "No action"),
   ("Ros", "ชม", "Praise"),
   ("Rabatt", "ส่วนลด", "Discount")],
  0, "easy", "30-soner er ofte beskyttende soner.", "เขต 30 เน้นเด็ก", "30 zones protect kids."),
Q("Hva er fordelen med å senke farten før sving?", "ชะลอก่อนโค้งดีอย่างไร?", "Slow before curve — why?",
  [("Bedre kontroll gjennom svingen", "คุมได้ดีในโค้ง", "Better control through curve"),
   ("Raskere tur", "เร็วขึ้น", "Faster trip"),
   ("Mer forbruk", "เปลืองขึ้น", "More fuel"),
   ("Slitasje", "สึกมาก", "More wear")],
  0, "easy", "Unngå utskridning/sladd.", "กันไถล", "Avoid skid."),
Q("Hva er 'lastegjennomgang' relevant for?", "\"ตรวจโหลด\" สำคัญเพราะ?", "Why is 'load check' relevant?",
  [("Fordeling og sikring påvirker stabilitet og bremselengde", "การกระจาย/การยึดส่งผลต่อความมั่นคง+ระยะเบรก", "Load balance affects stability & braking"),
   ("Bare estetikk", "ความสวย", "Just looks"),
   ("Ingen betydning", "ไม่สำคัญ", "Unimportant"),
   ("Bare under taket", "ใต้หลังคา", "Only under roof")],
  0, "hard", "Skjev last → skjev kjøring.", "โหลดเอียง = ขับเอียง", "Uneven load = uneven handling."),
Q("Hva er 'kryp' i kø?", "\"ค่อยๆ คืบ\" ใน fila?", "What is 'crawl' in traffic?",
  [("Kort-avstand bevegelse i saktegang", "เคลื่อนช้าๆ ใกล้", "Slow short-gap creep"),
   ("Svinge rundt", "วนรอบ", "Loop"),
   ("Bremse brått", "เบรกแรง", "Abrupt brake"),
   ("Gasse på", "เร่ง", "Accelerate")],
  0, "medium", "Hold rolig avstand og unngå plutselige bremser.", "เว้นคืบ นุ่มนวล", "Smooth crawl."),
Q("Hvorfor kan akselerasjon gi farlig kø?", "เร่งแรงก่อให้เกิด fila อันตรายได้อย่างไร?", "Hard accel → traffic risk?",
  [("Akselerasjon-bremsing skaper \"slange-effekt\"", "ทำให้รถหลัง fila เด้ง", "Creates slinky effect"),
   ("Kjøler bremsene", "เย็น", "Cools brakes"),
   ("Hjelper flyt", "ดีขึ้น", "Helps flow"),
   ("Sparer drivstoff", "ประหยัด", "Saves fuel")],
  0, "hard", "Jevn fart flyter best.", "fart นิ่งดีที่สุด", "Smooth speed flows best."),
]
DATA += B2
print(f"Batch 2 count: {len(B2)}")
print(f"Total so far: {len(DATA)}")

async def insert(db, items):
    ins = 0
    skp = 0
    for r in items:
        qno = r["q"]["no"].strip()
        if await db.questions.find_one({"question.no": qno}):
            skp += 1
            continue
        doc = {
            "id": str(uuid.uuid4()),
            "question": r["q"],
            "options": [{"id": LETTERS[i], "text": r["opts"][i]} for i in range(4)],
            "correctOptionId": r["correct"],
            "explanation": r["expl"],
            "bildeUrl": None,
            "category": "Situations",
            "difficulty": r["difficulty"],
            "active": True,
            "schema_version": 2,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Hand-crafted from PDF themes (part 1)",
        }
        await db.questions.insert_one(doc)
        ins += 1
    return ins, skp

async def main():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    before = await db.questions.count_documents({})
    print(f"Before: {before}")
    ins, skp = await insert(db, DATA)
    print(f"Inserted: {ins}, Skipped: {skp}")
    after = await db.questions.count_documents({})
    sit = await db.questions.count_documents({"category": "Situations"})
    print(f"After: {after}, Situations: {sit}")
    client.close()

asyncio.run(main())
