"""Seed batch 3+4: Communication/Position + Complex (90 Qs) to reach 500."""
import asyncio, os, uuid
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()
MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

LETTERS = ["A", "B", "C", "D"]

def Q(no_q, th_q, en_q, opts, correct, diff, no_e, th_e, en_e):
    return {
        "q": {"no": no_q, "th": th_q, "en": en_q},
        "opts": [{"no": o[0], "th": o[1], "en": o[2]} for o in opts],
        "correct": LETTERS[correct],
        "difficulty": diff,
        "expl": {"no": no_e, "th": th_e, "en": en_e},
    }

DATA = []

# ===== BATCH 3: COMMUNICATION & POSITION (45) =====
DATA += [
Q("Når skal du bruke blinklyset?", "เปิดไฟเลี้ยวเมื่อใด?", "When to use turn signal?",
  [("Ved all retningsendring og feltskifte", "ทุกครั้งที่เปลี่ยนทิศ/เลน", "All direction/lane changes"),
   ("Bare i by", "เฉพาะในเมือง", "City only"),
   ("Aldri", "ไม่เคย", "Never"),
   ("Kun natt", "กลางคืน", "Night only")],
  0, "easy", "Signalgir forutsigbarhet til andre.", "บอกคนอื่นให้รู้", "Predictability for others."),
Q("Hvor lenge før sving bør du blinke?", "ก่อนเลี้ยวนานแค่ไหนต้องเปิดไฟ?", "How long before turn to signal?",
  [("Minst 3 sekunder — gi andre tid", "อย่างน้อย 3 วินาที", "At least 3 seconds"),
   ("Samtidig som sving", "พร้อมเลี้ยว", "At the turn"),
   ("Etter sving", "หลังเลี้ยว", "After turn"),
   ("Aldri", "ไม่เคย", "Never")],
  0, "easy", "Gi andre tid til å forstå og reagere.", "ให้เวลาคนอื่นเตรียม", "Give others time."),
Q("Hvordan plasserer du deg før venstresving i kryss?", "ก่อนเลี้ยวซ้ายในแยก?", "Position before left turn at junction?",
  [("Så langt til venstre som mulig i ditt felt", "ชิดซ้ายในเลน", "Far left in your lane"),
   ("Midt i feltet", "กลาง", "Middle"),
   ("Til høyre", "ชิดขวา", "Right"),
   ("På motsatt side", "ฝั่งตรงข้าม", "Opposite side")],
  0, "medium", "Gir bedre sikt og rom for møtende.", "ให้สวนได้สะดวก", "Room for oncoming."),
Q("Hvordan plasserer du deg før høyresving?", "ก่อนเลี้ยวขวา?", "Position before right turn?",
  [("Så langt til høyre som mulig", "ชิดขวา", "Far right"),
   ("Midt", "กลาง", "Middle"),
   ("Venstre", "ซ้าย", "Left"),
   ("På fortau", "ทางเท้า", "Sidewalk")],
  0, "easy", "Unngå at noen smetter inn på innersiden.", "กันคนแทรก", "Prevent inside squeeze."),
Q("Hvor plasserer du deg på rett strekning?", "บนทางตรงควรอยู่ตรงไหน?", "Position on straight road?",
  [("Midt i eget kjørefelt", "กลางเลนของตัว", "Middle of your lane"),
   ("På midtlinjen", "เส้นกลาง", "Center line"),
   ("På vegskulderen", "ไหล่ทาง", "Shoulder"),
   ("På kantlinjen", "เส้นขอบ", "Edge line")],
  0, "easy", "Balanse gir rom i begge retninger.", "ได้ระยะทั้งสองข้าง", "Balance both sides."),
Q("Når har du vikeplikt for høyre?", "ให้ทางขวาเมื่อใด?", "Yield to right when?",
  [("I kryss uten skilt eller regulering", "แยกไม่มีป้าย", "At unmarked junction"),
   ("Alltid", "เสมอ", "Always"),
   ("Aldri", "ไม่เคย", "Never"),
   ("Bare på motorvei", "เฉพาะมอเตอร์เวย์", "Motorway only")],
  0, "easy", "Høyreregelen gjelder der annet ikke er regulert.", "ไม่มีป้ายใช้กฎขวา", "Right-hand rule w/o other rules."),
Q("Når har du vikeplikt uansett retning?", "ต้องให้ทางเสมอเมื่อใด?", "Yield regardless of direction when?",
  [("Ved vikepliktskilt og vikelinje", "เห็นป้ายหรือเส้น", "At yield sign/line"),
   ("Aldri", "ไม่เคย", "Never"),
   ("På rett vei", "บนทางตรง", "On straight"),
   ("På motorvei", "มอเตอร์เวย์", "Motorway")],
  0, "easy", "Skilt og oppmerking overstyrer høyreregel.", "ป้ายมีผลเหนือกฎขวา", "Signs override right-rule."),
Q("Hva gjør du hvis noen signaliserer takk etter du ga plass?", "คนขอบคุณเมื่อให้ทางควรทำอย่างไร?", "Someone thanks you after you gave way?",
  [("Smil og fokuser videre på trafikken", "ยิ้มและตั้งใจขับต่อ", "Smile and keep focus"),
   ("Stoppe helt", "หยุดสนิท", "Full stop"),
   ("Rope tilbake", "ตะโกน", "Shout back"),
   ("Ignorere fullstendig", "ไม่สนใจ", "Totally ignore")],
  0, "easy", "God samhandling — hold fokus på kjøringen.", "ร่วมมือกัน", "Cooperative driving."),
Q("Hva betyr \"blikk-kontakt\" i trafikken?", "\"สบตา\" ในจราจรคือ?", "Eye contact in traffic?",
  [("Bekrefte at andre har sett deg", "ยืนยันว่าฝ่ายตรงข้ามเห็น", "Confirm others saw you"),
   ("Flørting", "จีบ", "Flirting"),
   ("Trussel", "ข่มขู่", "Threat"),
   ("Tull", "เล่น", "Jokes")],
  0, "medium", "Spesielt viktig med myke trafikanter.", "สำคัญมากกับคนเดิน", "Critical with pedestrians."),
Q("Når er det lov å bruke horn?", "ใช้แตรได้เมื่อใด?", "When use horn?",
  [("For å varsle om fare", "เตือนอันตราย", "To warn of danger"),
   ("For å klage", "บ่น", "To complain"),
   ("Før forbikjøring i by", "ก่อนแซงในเมือง", "Before urban overtake"),
   ("Uten grunn", "ไม่มีเหตุ", "No reason")],
  0, "easy", "Horn = fare-varsler, ikke ergrelse.", "แตรเพื่อเตือน ไม่ใช่ระบาย", "Horn warns, not vents."),
Q("Hva er lyssignal (blink med fjernlys) brukt til?", "ไฟกระพริบใช้เพื่ออะไร?", "Flashing high beams for?",
  [("Varsle din tilstedeværelse", "แสดงตัว", "Announce presence"),
   ("Gi forkjørsrett", "ให้สิทธิ์", "Give priority"),
   ("Kreve plass", "ขอทาง", "Demand"),
   ("Straff", "ลงโทษ", "Punish")],
  0, "medium", "Aldri for å tvinge seg fram.", "ห้ามใช้บีบ", "Never to force past."),
Q("Hva gjør du i rundkjøring med flere felt?", "วงเวียนหลายเลนควรทำอย่างไร?", "Multi-lane roundabout?",
  [("Velg riktig felt før du går inn", "เลือกเลนก่อนเข้า", "Pick correct lane before entering"),
   ("Velg ved utkjøring", "เลือกตอนออก", "Pick at exit"),
   ("Bytte tilfeldig", "สุ่ม", "Randomly"),
   ("Kjøre midt", "ขับกลาง", "Straddle")],
  0, "medium", "Skilting viser hvilket felt som fører hvor.", "ดูป้าย", "Signs tell you which lane."),
Q("Hva gjør du når lastebil svinger høyre foran deg?", "รถบรรทุกเลี้ยวขวาหน้าคุณ?", "Truck turning right ahead?",
  [("Vent bak — ikke gå inn på høyre siden", "รออยู่ข้างหลัง ห้ามเข้าด้านขวา", "Wait behind — don't slip on right"),
   ("Kjøre forbi på høyre", "แซงขวา", "Pass on right"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Gå inn i blindsonen", "เข้าจุดอับ", "Enter blind spot")],
  0, "medium", "Tunge kjøretøy har stor blindsone høyre.", "จุดอับขวาของรถใหญ่", "Big trucks have big blind spots."),
Q("Hva gjør syklister i trafikken du må være ekstra obs på?", "จักรยานที่ต้องระวังอะไร?", "Cyclists — what to watch for?",
  [("De kan svinge uten å tegne", "อาจเลี้ยวโดยไม่ให้สัญญาณ", "May turn without signaling"),
   ("Aldri faller", "ไม่ล้ม", "Never fall"),
   ("Ikke bruker vei", "ไม่ใช้ถนน", "Not on road"),
   ("Kun fortau", "เฉพาะทางเท้า", "Sidewalks only")],
  0, "medium", "Gi ekstra rom og tålmodighet.", "ให้พื้นที่", "Give space and patience."),
Q("Hva betyr \"tegn\" fra politi?", "สัญญาณจากตำรวจหมายถึง?", "Police signal means?",
  [("Overstyrer skilt og trafikklys", "มีผลเหนือป้ายและไฟ", "Overrides signs & lights"),
   ("Valgfritt å følge", "เลือกได้", "Optional"),
   ("Samme som skilt", "เหมือนป้าย", "Same as signs"),
   ("Bare veiledning", "แค่แนะนำ", "Only guidance")],
  0, "easy", "Politiets tegn = øverste autoritet.", "ตำรวจสำคัญสุด", "Police = top authority."),
Q("Hvordan bruker du blikk før feltskifte?", "ก่อนเปลี่ยนเลนมองอย่างไร?", "Look sequence before lane change?",
  [("Speil → blindsone → blinklys → skift", "กระจก→จุดอับ→ไฟเลี้ยว→เปลี่ยน", "Mirror → blind spot → signal → move"),
   ("Skift først", "เปลี่ยนก่อน", "Move first"),
   ("Bare speil", "กระจก", "Only mirror"),
   ("Bare blink", "เปิดไฟ", "Only signal")],
  0, "medium", "SBSS: spille, blink, skulder, skift.", "กระจก-จุดอับ-ไฟ-เปลี่ยน", "MSM + blind spot."),
Q("Hva gjør du hvis fotgjenger venter ved gangfelt?", "คนรอที่ทางม้าลาย?", "Pedestrian waiting at crossing?",
  [("Stopp og la dem gå", "หยุดให้ข้าม", "Stop and let them cross"),
   ("Holde fart", "คงที่", "Keep speed"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Overse", "ไม่สน", "Ignore")],
  0, "easy", "Fotgjengere har prioritet ved gangfelt.", "คนเดินมาก่อน", "Pedestrians have priority."),
Q("Hva er lov ved blinkende gult lys?", "ไฟเหลืองกระพริบคือ?", "Flashing yellow light?",
  [("Kjør med forsiktighet", "ขับระวัง", "Proceed with caution"),
   ("Stopp", "หยุด", "Stop"),
   ("Full fart", "เต็มที่", "Full speed"),
   ("Parkere", "จอด", "Park")],
  0, "easy", "Signaler er enten ute av drift eller varsel.", "ระวังเป็นพิเศษ", "Caution — signals off or warning."),
Q("Hva er lov ved fast gult lys?", "ไฟเหลืองนิ่ง?", "Steady yellow?",
  [("Stopp, med mindre farlig å bremse", "หยุด ถ้าไม่อันตราย", "Stop unless unsafe"),
   ("Full fart", "เร่ง", "Speed through"),
   ("Vend", "กลับรถ", "U-turn"),
   ("Snu", "หันหัว", "Turn")],
  0, "easy", "Gult = forbered stopp.", "เหลือง = เตรียมหยุด", "Yellow = prepare to stop."),
Q("Hvordan gir du tegn til fotgjenger som skal krysse?", "ให้สัญญาณคนข้ามอย่างไร?", "Signal to crossing pedestrian?",
  [("Stopp tydelig og gi blikkontakt", "หยุดชัดเจน สบตา", "Stop clearly, eye contact"),
   ("Vinke vilt", "โบกใหญ่", "Wave wildly"),
   ("Tute", "บีบแตร", "Honk"),
   ("Vente uten kommunikasjon", "รอเงียบๆ", "Wait silently")],
  0, "medium", "Tydelig stopp + blikk bekrefter.", "หยุดชัด+สบตา", "Clear stop + eye contact."),
Q("Hva bør du gjøre ved møte på smal vei?", "สวนบนถนนแคบ?", "Meeting on narrow road?",
  [("Tilpass fart og finn møteplass hvis trengs", "ลดความเร็วและหาที่หลีก", "Slow and find passing spot"),
   ("Holde fart", "คงที่", "Keep speed"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Overkjøre", "ขับผ่าน", "Drive over")],
  0, "medium", "Tålmodighet og samarbeid løser det.", "อดทนและช่วยกัน", "Patience + cooperation."),
Q("Når er det ok å bruke fjernlys?", "เปิดไฟสูงเมื่อใด?", "When use high beams?",
  [("Når ingen møtende eller bil foran", "ไม่มีสวน/หน้าเรา", "No oncoming/ahead"),
   ("I tettbygd", "ในเมือง", "In city"),
   ("Møtende trafikk", "มีสวน", "Oncoming"),
   ("Tåke", "หมอก", "Fog")],
  0, "medium", "Unngå å blende andre.", "อย่าแยงตา", "Don't blind others."),
Q("Hva er riktig avstand til fotgjenger på fortau når du svinger?", "ระยะห่างคนเดินเมื่อเลี้ยว?", "Distance to pedestrian on sidewalk when turning?",
  [("Gi god margin", "เผื่อเว้นระยะ", "Give wide margin"),
   ("Kjøre på kanten", "ขับชิด", "Drive close"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Bruke horn", "บีบแตร", "Honk")],
  0, "easy", "De kan ta et steg til siden.", "อาจก้าวออกมา", "They may step out."),
Q("Hva betyr gul stripemaling i kjørebanen?", "เส้นเหลืองในเลนคือ?", "Yellow stripe in lane?",
  [("Midlertidig oppmerking (veiarbeid)", "ชั่วคราว (ก่อสร้าง)", "Temporary (roadworks)"),
   ("Permanent", "ถาวร", "Permanent"),
   ("Ingen betydning", "ไม่สำคัญ", "Not important"),
   ("Parkering", "จอด", "Parking")],
  0, "medium", "Midlertidig gul overstyrer hvit.", "เหลืองชั่วคราวมีผลเหนือขาว", "Temp yellow overrides white."),
Q("Hva gjør du når møtende blinker fjernlys mot deg?", "สวนทางกระพริบไฟสูงใส่เรา?", "Oncoming flashes high beams at you?",
  [("Sjekk om du har fjernlys på", "ตรวจไฟสูงของตัวเอง", "Check if yours is on"),
   ("Svare med fjernlys", "ตอบด้วยไฟสูง", "Flash back"),
   ("Øke fart", "เร่ง", "Speed up"),
   ("Ignorere", "ไม่สน", "Ignore")],
  0, "medium", "De kan varsle — fare, kontroll, eller blending.", "อาจเตือน", "May be warning you."),
Q("Hva bør du gjøre før du rygger?", "ก่อนถอยรถควรทำอะไร?", "Before reversing?",
  [("Se bak, sjekk blindsoner, vurder barn", "มองหลัง ระวังเด็ก", "Look behind, check blind spots, watch for kids"),
   ("Bruke bare speil", "ใช้กระจก", "Only mirrors"),
   ("Stol på ryggekamera alene", "เชื่อกล้องหลัง", "Trust backup camera only"),
   ("Full fart", "เร็ว", "Fast")],
  0, "medium", "Barn er vanskelig å se — gå rundt bilen først.", "เด็กมองไม่เห็น", "Kids hard to see."),
Q("Hva er riktig plassering i enfeltet rundkjøring?", "วงเวียน 1 เลนควรอยู่ตรงไหน?", "Single-lane roundabout position?",
  [("Midt i feltet — ingen felter å velge", "กลางเลน", "Middle of lane"),
   ("Venstre kant", "ชิดซ้าย", "Left edge"),
   ("Høyre kant", "ชิดขวา", "Right edge"),
   ("Utenfor", "นอกวงเวียน", "Outside")],
  0, "easy", "Én bane — hold midten.", "เลนเดียว อยู่กลาง", "One lane, stay centered."),
Q("Hva er det sikreste tidspunktet å kjøre?", "เวลาปลอดภัยที่สุดที่จะขับ?", "Safest time to drive?",
  [("Dag, tørt, lite trafikk", "กลางวัน แห้ง คนน้อย", "Day, dry, light traffic"),
   ("Natt", "กลางคืน", "Night"),
   ("Regnstorm", "พายุฝน", "Storm"),
   ("Fredag kveld", "ศุกร์เย็น", "Friday eve")],
  0, "easy", "Statistisk sett færrest ulykker.", "สถิติอุบัติเหตุน้อย", "Statistically safest."),
Q("Hva bør du gjøre hvis nødhjelpbil kommer bakfra med sirene?", "รถพยาบาลเปิดไซเรนมาจากด้านหลัง?", "Emergency vehicle w/ siren behind?",
  [("Flytt til siden og stopp hvis mulig", "หลบข้างและหยุด", "Pull over and stop if possible"),
   ("Holde fart", "คงที่", "Keep speed"),
   ("Kjøre fortere", "เร่ง", "Speed up"),
   ("Stoppe i midten", "หยุดกลาง", "Stop in middle")],
  0, "easy", "Gi utrykningskjøretøy fri vei.", "ให้ทางฉุกเฉิน", "Clear way for emergency."),
Q("Hva er riktig i motorveiavkjøring?", "ทางออกมอเตอร์เวย์ควรทำอย่างไร?", "Motorway exit?",
  [("Blink, gå til høyre felt tidlig, senk fart etter utkjøring", "เปิดไฟ เข้าเลนขวาแต่เนิ่น ลด fart หลังออก", "Signal, move right early, slow after exit"),
   ("Brems hardt på motorvei", "เบรกแรงบนมอเตอร์เวย์", "Hard brake on motorway"),
   ("Skift felt brått", "เปลี่ยนเลนกะทันหัน", "Sudden lane change"),
   ("Ingen blink", "ไม่เปิดไฟ", "No signal")],
  0, "medium", "Hold motorveifart fram til avkjørselen.", "คง fart จนถึงทางออก", "Keep motorway speed till ramp."),
Q("Hva er riktig i motorvei-påkjøring?", "ทางขึ้นมอเตอร์เวย์ควรทำอย่างไร?", "Motorway on-ramp?",
  [("Akselerer til trafikkens fart og smelt inn", "เร่งเท่า fart รถบนเลนแล้วแทรก", "Match speed and merge"),
   ("Stopp og vent", "หยุดรอ", "Stop and wait"),
   ("Lav fart", "ช้า", "Low speed"),
   ("Merge uten å se", "แทรกไม่ดู", "Merge blindly")],
  0, "medium", "Smidig sammensmelting er trygt og flytende.", "แทรกนุ่มนวล", "Smooth merge is safe."),
Q("Hva er riktig når trikk kommer i samme retning?", "รถรางทิศเดียวกัน?", "Tram in same direction?",
  [("La trikken passere — den følger spor", "ให้ผ่าน เพราะวิ่งราง", "Let it pass — tracks"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Kjøre foran", "ขับนำ", "Cut ahead"),
   ("Kjøre i sporet", "ขับในราง", "Drive on tracks")],
  0, "medium", "Trikk har ofte særskilt regulering.", "มักมีกฎพิเศษ", "Often special rules."),
Q("Hva er gult bakre lys på bil?", "ไฟเลี้ยวท้ายคือ?", "Yellow rear light?",
  [("Blinklys — retningsendring", "ไฟเลี้ยว", "Turn indicator"),
   ("Bremselys", "ไฟเบรก", "Brake"),
   ("Tåkelys", "ไฟตัดหมอก", "Fog"),
   ("Ryggelys", "ไฟถอย", "Reverse")],
  0, "easy", "Blinklys er gule både foran og bak.", "ไฟเลี้ยวเหลืองทั้งหน้า/หลัง", "Amber indicators front & back."),
Q("Hva betyr røde bremselys som blinker kraftig?", "ไฟเบรกกระพริบแรง?", "Strong flashing brake lights?",
  [("Nødbremsvarsling", "เตือนเบรกฉุกเฉิน", "Emergency brake warning"),
   ("Blinklys", "ไฟเลี้ยว", "Turn signal"),
   ("Tåkelys", "ตัดหมอก", "Fog"),
   ("Feil", "เสีย", "Fault")],
  0, "medium", "Varsle bilene bak om brå bremsing.", "เตือนเบรกกะทันหัน", "Warn of hard braking."),
Q("Hva betyr at noen svinger uten å blinke?", "ไม่เปิดไฟเลี้ยวตอนเลี้ยวคือ?", "Turning without signaling?",
  [("Ulovlig og farlig", "ผิดและเสี่ยง", "Illegal and risky"),
   ("Greit hvis rask", "โอเคถ้าเร็ว", "OK if quick"),
   ("Bedre", "ดีกว่า", "Better"),
   ("Normalt", "ปกติ", "Normal")],
  0, "easy", "Blinklys er lovpålagt.", "ต้องเปิดไฟ", "Signals required by law."),
Q("Hva gjør du ved innsnevring til ett felt?", "เลนลดเหลือหนึ่ง?", "Merging into one lane?",
  [("Glidelås — tur for tur", "สลับทีละคัน", "Zipper merge — alternate"),
   ("Kjøre foran", "นำ", "Cut in first"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Aldri slippe", "ห้ามให้", "Never yield")],
  0, "medium", "Glidelåsprinsippet gir beste flyt.", "หลักซิป", "Zipper merge works best."),
Q("Hva er riktig plassering ved kjøring med tilhenger?", "ลากพ่วงควรอยู่เลนใด?", "Trailer — lane position?",
  [("Hold høyre felt så mye som mulig", "ชิดขวา", "Keep right lane"),
   ("Venstre felt", "ซ้าย", "Left lane"),
   ("Midt", "กลาง", "Middle"),
   ("Skiftes mye", "สลับบ่อย", "Switch often")],
  0, "medium", "Lavere fart = høyre side.", "ช้ากว่าอยู่ขวา", "Slower = right side."),
Q("Når skal du blinke ved utkjøring fra rundkjøring?", "ออกจากวงเวียนเปิดไฟเมื่อใด?", "Roundabout exit signal?",
  [("Før avkjørsel ut av rundkjøringen", "ก่อนทางออก", "Before the exit"),
   ("Ved innkjøring", "ตอนเข้า", "At entry"),
   ("Aldri", "ไม่เคย", "Never"),
   ("Etter utkjøring", "หลังออก", "After exit")],
  0, "medium", "Blink høyre når du er forbi utkjøringen før din.", "เปิดไฟขวาก่อนทางออก", "Right signal before your exit."),
Q("Hvor plasserer du deg før rundkjøring når du skal rett fram?", "ก่อนวงเวียนไปตรง?", "Before roundabout going straight?",
  [("Høyre felt (oftest)", "เลนขวา", "Right lane (usually)"),
   ("Venstre", "ซ้าย", "Left"),
   ("Midt", "กลาง", "Middle"),
   ("Valgfritt", "ไม่สำคัญ", "Either")],
  0, "medium", "Avhenger av skilting — oftest høyre.", "ดูป้าย", "Depends on signs."),
Q("Hva gjør du når blind vinkel er dekket av A-stolpe?", "มุมอับของเสา A?", "Blind spot from A-pillar?",
  [("Bøy hodet frem/tilbake for å sjekke", "เอียงหัวดู", "Lean head to check"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Fjern stolpen", "ถอดเสา", "Remove pillar"),
   ("Kjøre fort", "เร่ง", "Speed up")],
  0, "medium", "A-stolpe kan skjule fotgjenger eller syklist.", "อาจบังคนเดิน/จักรยาน", "Pillar may hide pedestrian/cyclist."),
Q("Hva er riktig ved samhandling med busser?", "การทำงานร่วมกับรถบัส?", "Working with buses?",
  [("Gi plass når de signaliserer ut fra stopp (i tettbygd)", "ให้ทางตอนออกจากป้ายในเมือง", "Give way when leaving stop (urban)"),
   ("Kjøre forbi fort", "แซงไว", "Pass fast"),
   ("Bruke horn", "บีบแตร", "Honk"),
   ("Blokke dem", "กั้น", "Block them")],
  0, "medium", "Egen regel i tettbygd strøk.", "กฎในเมือง", "Urban-specific rule."),
Q("Hva er det farligste vanlig kommunikasjonsbrudd?", "การสื่อสารผิดที่อันตรายสุด?", "Most dangerous comm breakdown?",
  [("Ingen blinker ved retningsendring", "ไม่เปิดไฟเลี้ยว", "No signal on turn"),
   ("For høy radio", "เปิดเพลงดัง", "Loud radio"),
   ("For lange samtaler", "คุยนาน", "Long talks"),
   ("Uten kart", "ไม่มีแผนที่", "No map")],
  0, "medium", "Andre kan ikke lese tankene dine.", "คนอื่นไม่รู้ใจคุณ", "Others can't read minds."),
Q("Hva gjør du hvis noen stopper uventet foran deg?", "คันหน้าหยุดโดยไม่คาดฝัน?", "Car stops unexpectedly ahead?",
  [("Brems kontrollert og advar bak ved nødblink", "เบรกควบคุม+ไฟฉุกเฉิน", "Controlled brake + hazards"),
   ("Svinge brått", "หักหลบ", "Swerve hard"),
   ("Horn", "บีบแตร", "Horn"),
   ("Kjøre rundt uten blink", "อ้อมไม่บอก", "Go around w/o signal")],
  0, "medium", "Nødblink varsler kø for bilene bak.", "ไฟฉุกเฉินเตือนคันหลัง", "Hazards warn cars behind."),
Q("Hva er ditt ansvar ved avvikling?", "ความรับผิดชอบในความคล่องตัว?", "Responsibility for traffic flow?",
  [("Bidra til smidig flyt og tålmodighet", "ช่วยให้ไหลลื่น", "Contribute to smooth flow"),
   ("Vinne alle", "เอาชนะ", "Beat everyone"),
   ("Blokke", "กั้น", "Block"),
   ("Ignorere", "ไม่สน", "Ignore")],
  0, "easy", "Alle tjener på god samhandling.", "ทุกคนได้ประโยชน์", "Everyone wins with cooperation."),
]

# ===== BATCH 4: COMPLEX — NIGHT/WINTER/ACCIDENTS/TECH (45) =====
DATA += [
Q("Hva er hovedutfordringen med nattkjøring?", "ปัญหาหลักขับกลางคืน?", "Main night driving issue?",
  [("Redusert sikt og dybdesyn", "ทัศนวิสัยและมองมิติต่ำ", "Reduced visibility & depth"),
   ("For mange biler", "รถเยอะ", "Too many cars"),
   ("For få biler", "รถน้อย", "Too few cars"),
   ("For høy musikk", "เพลงดัง", "Loud music")],
  0, "easy", "Mørke gjør at du ser senere og feil.", "มืด=เห็นช้ากว่า", "Darkness = late vision."),
Q("Når bruker du fjernlys?", "เปิดไฟสูงเมื่อใด?", "When use high beam?",
  [("Uten møtende eller bil foran (ofte utenfor tettbygd)", "ไม่มีสวน/หน้าเรา", "No oncoming/lead car"),
   ("I tettbygd", "ในเมือง", "In city"),
   ("I tåke", "ในหมอก", "In fog"),
   ("Alltid", "เสมอ", "Always")],
  0, "easy", "Unngå å blende andre.", "อย่าแยงตา", "Don't dazzle others."),
Q("Hva gjør du ved møtende bil med fjernlys?", "สวนเปิดไฟสูง?", "Oncoming on high beam?",
  [("Se mot høyre kant, ikke direkte inn i lyset", "มองขอบขวา", "Look at right edge, not into light"),
   ("Se direkte", "มองตรง", "Look directly"),
   ("Blink tilbake", "ฟาดกลับ", "Flash back"),
   ("Øke fart", "เร่ง", "Speed up")],
  0, "medium", "Bevar natt-syn ved å flytte blikket.", "ย้ายสายตา", "Preserve night vision."),
Q("Hva gjør du som førstemann på ulykkesstedet?", "ถึงที่เกิดเหตุคนแรก?", "First at accident scene?",
  [("Sikre → varsle (113) → hjelpe", "ป้องกัน→แจ้ง→ช่วย", "Secure → alert → assist"),
   ("Kjøre forbi", "ขับผ่าน", "Drive past"),
   ("Ta bilder først", "ถ่ายรูปก่อน", "Take photos first"),
   ("Flytte biler", "ย้ายรถ", "Move cars")],
  0, "easy", "Prioritering er kritisk på ulykkessted.", "ลำดับสำคัญมาก", "Order of actions matters."),
Q("Hva er nødnummeret for ambulanse i Norge?", "หมายเลขฉุกเฉินพยาบาล?", "Ambulance number in Norway?",
  [("113", "113", "113"), ("110", "110", "110"), ("112", "112", "112"), ("911", "911", "911")],
  0, "easy", "110 brann, 112 politi, 113 ambulanse.", "110=ไฟ 112=ตำรวจ 113=พยาบาล", "110 fire, 112 police, 113 ambulance."),
Q("Hva er nødnummeret for politi i Norge?", "ฉุกเฉินตำรวจ?", "Police emergency in Norway?",
  [("112", "112", "112"), ("113", "113", "113"), ("110", "110", "110"), ("911", "911", "911")],
  0, "easy", "Politi = 112.", "ตำรวจ 112", "Police 112."),
Q("Hva er nødnummeret for brann i Norge?", "ฉุกเฉินไฟไหม้?", "Fire emergency in Norway?",
  [("110", "110", "110"), ("112", "112", "112"), ("113", "113", "113"), ("911", "911", "911")],
  0, "easy", "Brann = 110.", "ไฟไหม้ 110", "Fire 110."),
Q("Hva er viktig ved førstehjelp til bevisstløs?", "ปฐมพยาบาลคนหมดสติ?", "First aid for unconscious?",
  [("Sjekk åndedrett — sideleie hvis puster", "ตรวจหายใจ–ถ้าหายใจให้นอนตะแคง", "Check breathing — recovery position if breathing"),
   ("Flytt med makt", "ย้ายแรง", "Move forcefully"),
   ("Gi vann", "ให้น้ำ", "Give water"),
   ("Ignorere", "ไม่สน", "Ignore")],
  0, "medium", "Åpen luftvei + sideleie.", "เปิดทางเดินหายใจ", "Open airway + recovery."),
Q("Hva er piggdekkregel i Norge?", "กฎยางหนามในนอร์เวย์?", "Studded tire rule in Norway?",
  [("Tillatt 1. nov – 1. søndag etter påske (sør)", "อนุญาตฤดูหนาว", "Allowed in winter period"),
   ("Hele året", "ตลอดปี", "All year"),
   ("Aldri", "ไม่ได้", "Never"),
   ("Kun sommer", "ฤดูร้อน", "Summer only")],
  0, "hard", "Nordland/Troms/Finnmark har egne regler.", "ภาคเหนือมีกฎเอง", "Northern areas have own rules."),
Q("Hva er mønsterdybden på vinterdekk anbefalt?", "ดอกยางฤดูหนาวแนะนำ?", "Recommended winter tread depth?",
  [("Minst 3 mm", "อย่างน้อย 3 มม.", "At least 3 mm"),
   ("1 mm", "1", "1"),
   ("0,5 mm", "0.5", "0.5"),
   ("Ingen krav", "ไม่กำหนด", "None")],
  0, "medium", "Lovkrav 1,6 mm; 3 mm anbefalt om vinter.", "กฎ 1.6, แนะนำ 3", "Law 1.6; rec 3 winter."),
Q("Hva er ABS-bremser designet for?", "ABS มีไว้ทำไม?", "ABS designed for?",
  [("Unngå hjulblokkering og styremulighet ved nødbrems", "กันล้อล็อก ควบคุมได้", "Prevent wheel lock, keep steering"),
   ("Sjekk veien", "ตรวจถนน", "Check road"),
   ("Spare bensin", "ประหยัด", "Save fuel"),
   ("Øke fart", "เร่ง", "Speed up")],
  0, "medium", "Trykk hardt, hold styring — ABS gjør jobben.", "เหยียบแน่นและคุมพวงมาลัย", "Full press, keep steering."),
Q("Hvordan nødbremser du best med ABS?", "เบรกฉุกเฉินกับ ABS?", "Emergency brake with ABS?",
  [("Press pedalen helt inn og styr unna", "เหยียบเต็ม+หักหลบ", "Full pedal + steer"),
   ("Pumpe pedalen", "เหยียบเป็นจังหวะ", "Pump pedal"),
   ("Slipp og prøv igjen", "ปล่อย", "Release"),
   ("Bare styr", "หักอย่างเดียว", "Only steer")],
  0, "medium", "ABS ivaretar hjulkontakten automatisk.", "ABS ทำงานอัตโนมัติ", "ABS handles it."),
Q("Hva er ESP?", "ESP คือ?", "What is ESP?",
  [("Stabilitetskontroll — hindrer sladd", "ระบบเสถียร", "Stability control"),
   ("Tuningchip", "จูนเครื่อง", "Tuning chip"),
   ("Radio", "วิทยุ", "Radio"),
   ("Lysbryter", "สวิตช์ไฟ", "Light switch")],
  0, "medium", "Bremser hjul selektivt for å hjelpe kontroll.", "เบรกล้อแยกเพื่อคุม", "Selective wheel braking."),
Q("Hva betyr \"underskrinn\" ved forbikjøring?", "\"เสียเกาะขณะแซง\" คือ?", "'Understeer' when overtaking?",
  [("Bilen vil videre rett, skinner ikke inn", "รถไม่หักเข้า", "Car won't turn in"),
   ("Bilen skrens bak", "ท้ายปัด", "Rear slide"),
   ("Bilen stopper", "หยุด", "Stops"),
   ("Bilen roterer", "หมุน", "Rotates")],
  0, "hard", "Senk fart og reduser styreutslag.", "ลด fart ลดหัก", "Reduce speed and steering."),
Q("Hva er «overstyring»?", "\"overoversteer\" คือ?", "What is 'oversteer'?",
  [("Bilens bakpart glir ut i sving", "ท้ายเหวี่ยง", "Rear slides out in turn"),
   ("Styreratt for stort", "พวงมาลัยใหญ่", "Big wheel"),
   ("Bilen forkjører", "แซงเอง", "Self-overtake"),
   ("Ingen ting", "ไม่มี", "Nothing")],
  0, "hard", "Lett gass, korriger med ratt.", "ผ่อนคันเร่ง แก้พวง", "Ease throttle, correct steer."),
Q("Hva er refleksjonsbruk i mørke?", "สะท้อนแสงในที่มืด?", "Reflectors at night?",
  [("Gjør fotgjengere synlige fra langt hold", "ทำให้เห็นคนเดินจากไกล", "Makes pedestrians visible far"),
   ("Bare dekor", "เพื่อความสวย", "Just decoration"),
   ("Reflekterer varme", "สะท้อนความร้อน", "Reflects heat"),
   ("Kun nyttig om dagen", "ใช้กลางวัน", "Useful only by day")],
  0, "easy", "Dramatisk forbedring — 25 vs 125 m.", "ระยะ 25→125 ม.", "Dramatic: 25 vs 125 m."),
Q("Hva er typisk stoppelengde ved 50 km/t med god brems?", "ที่ 50 km/h เบรกดีระยะหยุด?", "Stop at 50 km/h?",
  [("~25 m", "~25", "~25"), ("~10 m", "~10", "~10"),
   ("~50 m", "~50", "~50"), ("~100 m", "~100", "~100")],
  0, "medium", "Reaksjon ~14 + brems ~14 ≈ 25–30 m.", "~25–30", "~25–30 m."),
Q("Hva gjør du ved brann i motorrommet?", "ไฟไหม้ห้องเครื่อง?", "Engine fire?",
  [("Stopp, slå av tenning, bruk brannslukker fra siden", "หยุด ดับเครื่อง ใช้ถังดับเพลิงด้านข้าง", "Stop, ignition off, extinguish from side"),
   ("Åpne panseret helt", "เปิดฝาปิดเต็ม", "Open hood fully"),
   ("Fortsett", "ขับต่อ", "Keep driving"),
   ("Vente på hjelp", "รอคนช่วย", "Wait for help")],
  0, "hard", "Åpen panser = økt lufttilførsel = verre brann.", "เปิดฝา=ไฟใหญ่ขึ้น", "Open hood = more air = bigger fire."),
Q("Hva gjør du når bremsene svikter?", "เบรกเสีย?", "Brake failure?",
  [("Gir ned, håndbrems gradvis, horn", "ลดเกียร์ เบรกมือค่อยๆ", "Downshift, handbrake gradual, honk"),
   ("Slippe alt", "ปล่อยทุกอย่าง", "Let go"),
   ("Brems med fot", "ใช้เท้า", "Foot brake"),
   ("Lukke øyne", "หลับตา", "Close eyes")],
  0, "hard", "Kombiner alle bremsealternativer trygt.", "ใช้ทุกวิธีรวมกัน", "Combine all braking safely."),
Q("Hva gjør du ved punktering i høy fart?", "ยางระเบิดที่ fart สูง?", "Blowout at high speed?",
  [("Hold rattet fast, slipp gass, finn plass å stoppe", "จับพวงแน่น ผ่อนคันเร่ง หาที่หลีก", "Hold wheel firm, ease throttle, pull over"),
   ("Brems hardt", "เบรกแรง", "Hard brake"),
   ("Svinge brått", "หักแรง", "Swerve"),
   ("Øke fart", "เร่ง", "Speed up")],
  0, "hard", "Hardt brems eller sving kan velte bilen.", "หักแรง/เบรกแรงอาจคว่ำ", "Hard maneuvers may flip."),
Q("Hva er riktig ved start av motor i kaldt vær?", "สตาร์ทเครื่องอากาศหนาว?", "Start in cold weather?",
  [("La den gå rolig et øyeblikk, så kjør forsiktig", "เดินเบา→ขับเบา", "Idle briefly, drive gently"),
   ("Full gass umiddelbart", "เหยียบเต็มทันที", "Full throttle now"),
   ("Vri om nøkkel flere ganger", "เปิด/ปิดหลายครั้ง", "Cycle key many times"),
   ("Ikke start", "อย่าสตาร์ท", "Don't start")],
  0, "medium", "Olje må nå delene før full last.", "น้ำมันต้องถึงทุกจุด", "Oil must reach parts."),
Q("Hva er fare ved lav oljenivå?", "น้ำมันเครื่องต่ำ?", "Low engine oil danger?",
  [("Motorhavari", "เครื่องพัง", "Engine damage"),
   ("Bedre gir", "เกียร์ดี", "Better gears"),
   ("Ingen", "ไม่มี", "None"),
   ("Mer fart", "แรงขึ้น", "More speed")],
  0, "medium", "Sjekk olje regelmessig.", "ตรวจน้ำมันสม่ำเสมอ", "Check regularly."),
Q("Hva gjør du ved tåke med mindre enn 100 m sikt?", "หมอกหนาไม่ถึง 100 ม.?", "Fog under 100 m visibility?",
  [("Nærlys + tåkelys + lav fart + stor avstand", "ไฟต่ำ+ตัดหมอก+ช้า+เว้นระยะ", "Low beam + fog + slow + gap"),
   ("Fjernlys", "ไฟสูง", "High beam"),
   ("Ingen lys", "ไม่ใช้ไฟ", "No lights"),
   ("Full fart", "เร็ว", "Fast")],
  0, "medium", "Fjernlys reflekteres i tåka og blender.", "ไฟสูงสะท้อนในหมอก", "High beams reflect in fog."),
Q("Hva er riktig dekk å bruke om vinteren?", "หน้าหนาวใช้ยางแบบใด?", "Right tires for winter?",
  [("Vinterdekk (med eller uten pigger)", "ยางหนาว (หนาม/ไม่หนาม)", "Winter tires (studded or not)"),
   ("Sommerdekk", "ยางร้อน", "Summer tires"),
   ("Regnerdekk", "ยางฝน", "Rain tires"),
   ("Bare felger", "แค่ขอบ", "Just rims")],
  0, "easy", "Pålagt i Norge ved vinterforhold.", "กฎบังคับฤดูหนาว", "Required in winter conditions."),
Q("Hva gjør du ved sladd i kurve?", "ไถลในโค้ง?", "Skid in curve?",
  [("Slipp gass, styr der du vil kjøre", "ผ่อน กำหนดพวง", "Ease off, steer where you want"),
   ("Brems hardt", "เบรกแรง", "Hard brake"),
   ("Øke fart", "เร่ง", "Speed up"),
   ("Løs rattet", "ปล่อยพวง", "Let wheel go")],
  0, "hard", "Se dit du vil — ikke på hindringen.", "มองไปจุดที่จะไป", "Look where you want."),
Q("Hva gjør du ved oversteer-sladd?", "ท้ายเหวี่ยง?", "Oversteer skid?",
  [("Styr motsatt av slades retning, slipp gass", "หักกลับทิศท้ายปัด ผ่อน", "Counter-steer, ease throttle"),
   ("Gasse på", "เร่ง", "Floor it"),
   ("Brems", "เบรก", "Brake"),
   ("Rett fram", "ตรง", "Straight")],
  0, "hard", "Korrigere riktig uten overdrivelse.", "แก้ไม่เกินขนาด", "Correct, don't overdo."),
Q("Hva gjør du når motoren stopper i kryss?", "เครื่องดับในแยก?", "Engine dies at junction?",
  [("Nødblink på, prøv å starte, skyv ut av vei om nødvendig", "ไฟฉุกเฉิน ลองสตาร์ท ผลักออก", "Hazards, restart, push out if needed"),
   ("Gå ut raskt", "ออกไปเร็ว", "Leave quickly"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Ring radio", "โทรวิทยุ", "Call radio")],
  0, "medium", "Sikre stedet før du løser problemet.", "ให้ปลอดภัยก่อน", "Safety first."),
Q("Hva er tegn på dårlige støtdempere?", "สัญญาณโช้คเสื่อม?", "Sign of bad shocks?",
  [("Bilen \"sviver\" lenge etter en humpe", "รถสั่นนานหลังผ่านลูกระนาด", "Car bounces after bump"),
   ("Raskere fart", "เร็วขึ้น", "Faster"),
   ("Lavere forbruk", "ประหยัด", "Less fuel"),
   ("Bedre bremser", "เบรกดี", "Better brakes")],
  0, "hard", "Utskiftede støtdempere = bedre veigrep.", "โช้คดี=เกาะดี", "Good shocks = better grip."),
Q("Når er det farlig å kjøre med snø på taket?", "หิมะบนหลังคารถอันตรายเมื่อใด?", "Danger of snow on roof?",
  [("Alltid — kan fly av og treffe andre", "อันตรายเสมอ ปลิวชนคนอื่นได้", "Always — can fly off, hit others"),
   ("Aldri", "ไม่อันตราย", "Never"),
   ("Bare i sol", "แดดเท่านั้น", "Only in sun"),
   ("Bare natt", "กลางคืน", "Night only")],
  0, "medium", "Fjern snø fra tak, panser og lys før kjøring.", "เคลียร์หิมะก่อนขับ", "Clear all snow before driving."),
Q("Hva er «parkering med hjul mot kantstein» hensikt?", "จอดเอียงล้อเข้าขอบทางเพื่ออะไร?", "Why turn wheels to curb when parking?",
  [("Hindrer bilen i å rulle dersom brems svikter", "กันรถไหล", "Prevents rollaway"),
   ("Bremser mer", "เบรกมากขึ้น", "More braking"),
   ("Lavere slitasje", "สึกน้อย", "Less wear"),
   ("Tryggere dekk", "ยางปลอดภัย", "Safer tires")],
  0, "medium", "I oppoverbakke: hjul fra kanten. Nedover: mot kanten.", "ขึ้น=ออก / ลง=เข้า", "Up=away / Down=toward."),
Q("Hva må du ha med i bilen i Norge (anbefalt)?", "ในรถควรมีอะไร (แนะนำ)?", "Recommended in car (Norway)?",
  [("Varseltriangel, refleksvest, førstehjelpsutstyr", "สามเหลี่ยมเตือน เสื้อสะท้อนแสง ปฐมพยาบาล", "Warning triangle, vest, first aid"),
   ("Kun radio", "วิทยุ", "Radio only"),
   ("Kun GPS", "GPS", "GPS only"),
   ("Ingen ting", "ไม่มี", "Nothing")],
  0, "easy", "Grunnleggende sikkerhetsutstyr.", "อุปกรณ์พื้นฐาน", "Basic safety kit."),
Q("Hva er tegn på dårlige bremser?", "สัญญาณเบรกไม่ดี?", "Sign of bad brakes?",
  [("Piping, rykking eller lang pedalvei", "เสียงดัง สะดุด เบรกหย่อน", "Squeal, judder, long pedal"),
   ("Stille", "เงียบ", "Silent"),
   ("Hard pedal", "แข็ง", "Hard pedal"),
   ("Raskt stopp", "หยุดเร็ว", "Quick stop")],
  0, "medium", "Sjekk bremsene regelmessig.", "ตรวจเบรก", "Check brakes."),
Q("Hva gjør du ved bilulykke med personer fanget?", "คนติดในรถหลังชน?", "People trapped in crash?",
  [("Ring 113, ikke flytt med mindre brann/vann", "โทร 113 ห้ามย้ายถ้าไม่จำเป็น", "Call 113, don't move unless fire/water"),
   ("Dra dem ut", "ดึงออก", "Pull them out"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Ta bilder", "ถ่ายรูป", "Take photos")],
  0, "medium", "Feil bevegelse kan forverre skader.", "ย้ายผิดอาจบาดเจ็บหนัก", "Wrong move worsens injury."),
Q("Hva kjennetegner en trygg kjørestil i snø?", "ขับในหิมะที่ปลอดภัย?", "Safe snow driving traits?",
  [("Myke bevegelser, jevn fart, stor avstand", "นุ่มนวล คงที่ เว้นระยะ", "Smooth moves, steady speed, wide gap"),
   ("Brå bremsing", "เบรกแรง", "Hard braking"),
   ("Hurtige sving", "หักเร็ว", "Quick turns"),
   ("Full gass", "เต็มที่", "Full throttle")],
  0, "easy", "Snø krever skånsom kjøring.", "หิมะต้องนุ่มนวล", "Snow needs gentleness."),
Q("Hva er «blanding» av nysne og is farligst?", "หิมะใหม่ผสมน้ำแข็งอันตรายเพราะ?", "Fresh snow on ice danger?",
  [("Ingen synlig varsel — null grep", "ดูไม่ออก เกาะ 0", "No warning — zero grip"),
   ("Bedre grep", "เกาะดี", "Better grip"),
   ("Lettere styring", "พวงมาลัยเบา", "Lighter steering"),
   ("Kortere stoppe", "หยุดสั้น", "Shorter stop")],
  0, "hard", "Svart is under snø = verste kombinasjon.", "น้ำแข็งใต้หิมะ", "Black ice under snow."),
Q("Hva er riktig ved lading av elbil underveis?", "ชาร์จ EV ขณะเดินทาง?", "Charging EV on the go?",
  [("Planlegg stopp på hurtigladere", "วางแผนจุดชาร์จเร็ว", "Plan fast-charge stops"),
   ("Stoppe tilfeldig", "หยุดสุ่ม", "Random stops"),
   ("Lade hjemme bare", "ชาร์จบ้านอย่างเดียว", "Home only"),
   ("Aldri", "ไม่ต้อง", "Never")],
  0, "easy", "Planlegging gir trygg langtur.", "วางแผนดีขับไกลได้", "Plan = safe long trip."),
Q("Hvorfor er oppvarmingsperioden viktig i kaldt vær?", "ทำไมต้องอุ่นเครื่องหน้าหนาว?", "Why warm-up in cold?",
  [("Olje må nå alle deler før full last", "น้ำมันต้องถึงทุกจุด", "Oil must reach all parts"),
   ("For utseende", "สวย", "For looks"),
   ("Batteriet", "แบต", "Battery"),
   ("Radioen", "วิทยุ", "Radio")],
  0, "medium", "Kort rolig kjøring i starten.", "เริ่มต้นขับเบาๆ", "Gentle start."),
Q("Hva er tegn på glatt vei uten at du ser det?", "ถนนลื่นแบบมองไม่เห็น?", "Slippery road signs?",
  [("Broer, skygger, rett etter regn når det fryser", "สะพาน เงา หลังฝนเริ่มเย็น", "Bridges, shadows, rain then freeze"),
   ("Tørre strekninger", "ถนนแห้ง", "Dry sections"),
   ("Ny asfalt", "ยางมะตอยใหม่", "New asphalt"),
   ("Svart asfalt", "ยางมะตอยดำ", "Black asphalt")],
  0, "hard", "Broer fryser først — vær ekstra obs.", "สะพานจะเย็นก่อน", "Bridges freeze first."),
Q("Hva er riktig rekkefølge ved start i oppoverbakke med manuell gir?", "ออกตัวขึ้นเขาเกียร์ธรรมดาลำดับ?", "Manual hill start order?",
  [("Håndbrems → clutch slippe sakte → gass → slipp håndbrems", "เบรกมือ→คลัตช์ช้าๆ→คันเร่ง→ปล่อย", "Handbrake → slow clutch → throttle → release"),
   ("Gass først", "เร่งก่อน", "Throttle first"),
   ("Skli bakover", "ไหลถอย", "Roll back"),
   ("Bytte gir", "เปลี่ยนเกียร์", "Change gear")],
  0, "hard", "Unngå rulling bakover.", "กันไหลถอย", "Prevent rollback."),
Q("Hva betyr rødt varsellys \"olje\" på dashbordet?", "ไฟเตือนน้ำมันเครื่อง?", "Oil warning light?",
  [("Stopp snarest — lavt trykk eller nivå", "หยุดทันที", "Stop asap — low pressure/level"),
   ("Ignorere", "ไม่สน", "Ignore"),
   ("Kjør mer", "ขับต่อ", "Keep driving"),
   ("Full gass", "เร่ง", "Floor it")],
  0, "medium", "Kan skade motoren alvorlig.", "เสี่ยงเครื่องพัง", "Major engine damage risk."),
Q("Hva betyr rødt \"temperatur\" varsellys?", "ไฟเตือนอุณหภูมิเครื่อง?", "Red temperature warning?",
  [("Motoren overopphetet — stopp", "เครื่องร้อน หยุด", "Engine overheat — stop"),
   ("Kald vær", "อากาศหนาว", "Cold weather"),
   ("Ingen fare", "ไม่เป็นไร", "No issue"),
   ("Gas-fyll", "เติมแก๊ส", "Fill gas")],
  0, "medium", "Stopp trygt, la motoren kjøle.", "หยุดให้เครื่องเย็น", "Stop, let cool."),
Q("Hva er risikoen ved gamle dekk (eldre enn 6 år)?", "ยางเก่า 6 ปี+?", "Risk of old tires (>6 yr)?",
  [("Gummien blir hard, dårligere grep", "ยางแข็ง เกาะน้อย", "Rubber hardens, less grip"),
   ("Bedre grep", "เกาะดี", "Better grip"),
   ("Lavere pris", "ราคาถูก", "Cheaper"),
   ("Ingen forskjell", "ไม่ต่าง", "No diff")],
  0, "medium", "Bytt dekk også om mønsteret virker ok.", "เปลี่ยนยางตามอายุ", "Replace by age too."),
Q("Hva sier vegtrafikkloven om fører og rus?", "กฎหมายว่าด้วยคนขับและสารเสพ?", "Traffic law on driver & intoxication?",
  [("Det er forbudt å føre kjøretøy i påvirket tilstand", "ห้ามขับขณะมึนเมา", "Driving while impaired is prohibited"),
   ("Ok med lite", "นิดหน่อยโอเค", "A little is OK"),
   ("Bare med førerkort", "เฉพาะมีใบขับ", "Only with license"),
   ("Bare natt", "กลางคืน", "Night only")],
  0, "easy", "Uansett middel — rus = forbud.", "สารใดก็ห้าม", "Any impairment = prohibited."),
Q("Hva må gjøres ved skade på annet kjøretøy (parkering)?", "ชนรถที่จอดอยู่?", "Hit a parked car?",
  [("Legge igjen kontaktinfo eller melde til politi", "ให้เบอร์/แจ้งตำรวจ", "Leave contact or notify police"),
   ("Kjøre videre", "ขับไป", "Drive off"),
   ("Ingen ting", "ไม่ต้องทำ", "Nothing"),
   ("Ta bilder og dra", "ถ่ายรูปและจากไป", "Photo & leave")],
  0, "easy", "Lovpålagt opplysningsplikt.", "ต้องแจ้ง", "Legally required to notify."),
]

print(f"Data count: {len(DATA)}")

async def insert(db, items):
    ins = skp = 0
    for r in items:
        qno = r["q"]["no"].strip()
        if await db.questions.find_one({"question.no": qno}):
            skp += 1
            continue
        doc = {
            "id": str(uuid.uuid4()),
            "question": r["q"],
            "options": [{"id": LETTERS[i], "text": r["opts"][i]} for i in range(4)],
            "correctOptionId": r["correct"],
            "explanation": r["expl"],
            "bildeUrl": None,
            "category": "Situations",
            "difficulty": r["difficulty"],
            "active": True,
            "schema_version": 2,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source": "Hand-crafted from PDF themes (part 2)",
        }
        await db.questions.insert_one(doc)
        ins += 1
    return ins, skp

async def main():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    before = await db.questions.count_documents({})
    print(f"Before: {before}")
    ins, skp = await insert(db, DATA)
    print(f"Inserted: {ins}, Skipped: {skp}")
    after = await db.questions.count_documents({})
    sit = await db.questions.count_documents({"category": "Situations"})
    print(f"After: {after}, Situations total: {sit}")
    client.close()

asyncio.run(main())
