"""Seed new questions batch mapped to v2 schema."""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid, os
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

LETTERS = ["A", "B", "C", "D"]

RAW = [
{"sporsmal":{"no":"Du nærmer deg et gangfelt uten lys. En fotgjenger står ved kanten. Hva er riktig?","th":"ใกล้ทางม้าลายไม่มีไฟ คนยืนรอ คุณควรทำอย่างไร?","en":"Approaching an unmarked crosswalk with a waiting pedestrian. What is correct?"},"alternativer":[{"text":{"no":"Fortsette hvis du er først","th":"ไปต่อถ้าคุณมาก่อน","en":"Continue if you arrived first"}},{"text":{"no":"Stoppe og slippe fotgjengeren over","th":"หยุดให้คนข้าม","en":"Stop and let the pedestrian cross"}},{"text":{"no":"Blinke med lys","th":"กระพริบไฟ","en":"Flash lights"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}}],"riktigSvar":"B","forklaring":{"no":"Fotgjengere i gangfelt har prioritet.","th":"คนข้ามมีสิทธิ์ก่อน","en":"Pedestrians have priority at crosswalks"}},
{"sporsmal":{"no":"Du kjører i 80-sone på våt vei. Hva er riktig tilpasning?","th":"ถนนเปียก 80 ควรทำอย่างไร?","en":"80 km/h zone on wet road—what is correct?"},"alternativer":[{"text":{"no":"Holde 80","th":"คง 80","en":"Keep 80"}},{"text":{"no":"Øke fart for stabilitet","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Redusere fart og øke avstand","th":"ลดความเร็วและเว้นระยะ","en":"Reduce speed and increase distance"}},{"text":{"no":"Bremse sent","th":"เบรกช้า","en":"Brake late"}}],"riktigSvar":"C","forklaring":{"no":"Våt vei gir lengre bremselengde.","th":"ถนนเปียกหยุดยาก","en":"Wet roads increase stopping distance"}},
{"sporsmal":{"no":"I en rundkjøring med to felt skal du rett frem. Hvilket felt er best?","th":"วงเวียน 2 เลน ไปตรงควรเลือกเลนไหน?","en":"Two-lane roundabout going straight—best lane?"},"alternativer":[{"text":{"no":"Alltid høyre","th":"ขวาเสมอ","en":"Always right"}},{"text":{"no":"Alltid venstre","th":"ซ้ายเสมอ","en":"Always left"}},{"text":{"no":"Begge kan brukes – følg skilting/oppmerking","th":"ใช้ได้ทั้งสองตามป้าย/เส้น","en":"Either—follow signs/markings"}},{"text":{"no":"Midten","th":"กลาง","en":"Middle"}}],"riktigSvar":"C","forklaring":{"no":"Følg lokal skilting/oppmerking.","th":"ดูป้าย/เส้น","en":"Follow local signage/markings"}},
{"sporsmal":{"no":"Du skal kjøre forbi en syklist. Hva er riktig sideavstand?","th":"แซงจักรยานควรเว้นระยะเท่าไร?","en":"Overtaking a cyclist—correct lateral distance?"},"alternativer":[{"text":{"no":"Minst 0,5 m","th":"อย่างน้อย 0.5 ม.","en":"At least 0.5 m"}},{"text":{"no":"Minst 1,0 m","th":"อย่างน้อย 1.0 ม.","en":"At least 1.0 m"}},{"text":{"no":"Minst 1,5 m der mulig","th":"ประมาณ 1.5 ม. ถ้าเป็นไปได้","en":"About 1.5 m where possible"}},{"text":{"no":"Ingen krav","th":"ไม่มีข้อกำหนด","en":"No requirement"}}],"riktigSvar":"C","forklaring":{"no":"God sideavstand øker sikkerheten.","th":"เว้นระยะปลอดภัย","en":"Adequate lateral distance improves safety"}},
{"sporsmal":{"no":"Du nærmer deg en buss som blinker ut fra holdeplass i tettbygd strøk. Hva er riktig?","th":"รถบัสกำลังออกจากป้ายในเมือง ควรทำอย่างไร?","en":"Bus indicating out of a stop in urban area—what is correct?"},"alternativer":[{"text":{"no":"Kjøre forbi raskt","th":"แซงเร็ว","en":"Pass quickly"}},{"text":{"no":"Gi plass og slippe ut","th":"ให้ทาง","en":"Give way"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Du skal lette bussens utkjøring.","th":"ให้รถบัสออก","en":"Facilitate bus re-entry"}},
{"sporsmal":{"no":"Hva er korrekt ved bruk av tåkelys foran?","th":"ไฟตัดหมอกหน้าควรใช้เมื่อใด?","en":"Front fog lights—when to use?"},"alternativer":[{"text":{"no":"Alltid i mørke","th":"เสมอในที่มืด","en":"Always at night"}},{"text":{"no":"Ved redusert sikt (tåke/snø/regn)","th":"เมื่อทัศนวิสัยต่ำ","en":"In reduced visibility"}},{"text":{"no":"Kun på motorvei","th":"เฉพาะมอเตอร์เวย์","en":"Motorway only"}},{"text":{"no":"Aldri","th":"ไม่เคย","en":"Never"}}],"riktigSvar":"B","forklaring":{"no":"Brukes ved dårlig sikt.","th":"ใช้เมื่อมองไม่ชัด","en":"Use in poor visibility"}},
{"sporsmal":{"no":"Du kjører ned en lang bakke. Hva er riktig teknikk?","th":"ลงเขายาวควรใช้เทคนิคใด?","en":"Long downhill—correct technique?"},"alternativer":[{"text":{"no":"Fri gir","th":"เกียร์ว่าง","en":"Neutral"}},{"text":{"no":"Kun bremsepedal","th":"ใช้เบรกอย่างเดียว","en":"Brake only"}},{"text":{"no":"Bruke lavere gir (motorbrems)","th":"ใช้เกียร์ต่ำ","en":"Use lower gear (engine braking)"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}}],"riktigSvar":"C","forklaring":{"no":"Motorbrems avlaster bremsene.","th":"ช่วยเบรก","en":"Engine braking reduces brake load"}},
{"sporsmal":{"no":"Hva er riktig plassering før høyresving i kryss uten oppmerking?","th":"ก่อนเลี้ยวขวาในแยกไม่มีเส้น ควรอยู่ตรงไหน?","en":"Position before right turn without markings?"},"alternativer":[{"text":{"no":"Til venstre","th":"ซ้าย","en":"Left"}},{"text":{"no":"Midt i feltet","th":"กลาง","en":"Middle"}},{"text":{"no":"Så langt til høyre som praktisk","th":"ชิดขวา","en":"As far right as practical"}},{"text":{"no":"På fortau","th":"ทางเท้า","en":"Sidewalk"}}],"riktigSvar":"C","forklaring":{"no":"Reduser konflikt med andre trafikanter.","th":"ลดความเสี่ยง","en":"Reduce conflicts"}},
{"sporsmal":{"no":"Hva betyr heltrukket sperrelinje ved siden av stiplet linje?","th":"เส้นทึบคู่กับเส้นประหมายถึงอะไร?","en":"Solid line next to dashed line means?"},"alternativer":[{"text":{"no":"Begge kan krysse","th":"ข้ามได้ทั้งคู่","en":"Both may cross"}},{"text":{"no":"Kun fra stiplet side","th":"ข้ามได้จากฝั่งเส้นประ","en":"Only from dashed side"}},{"text":{"no":"Kun fra heltrukket side","th":"ข้ามได้จากฝั่งทึบ","en":"Only from solid side"}},{"text":{"no":"Ingen kan krysse","th":"ห้ามทั้งคู่","en":"None may cross"}}],"riktigSvar":"B","forklaring":{"no":"Stiplet side kan krysse.","th":"ฝั่งเส้นประข้ามได้","en":"Dashed side may cross"}},
{"sporsmal":{"no":"Du nærmer deg et uoversiktlig bakketopp. Hva er riktig?","th":"ใกล้เนินที่มองไม่เห็น ควรทำอย่างไร?","en":"Approaching a blind crest—what is correct?"},"alternativer":[{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Forberede forbikjøring","th":"เตรียมแซง","en":"Prepare to overtake"}},{"text":{"no":"Redusere fart og være klar til å stoppe","th":"ลดความเร็วและพร้อมหยุด","en":"Reduce speed and be ready to stop"}},{"text":{"no":"Bruke horn kontinuerlig","th":"บีบแตรตลอด","en":"Use horn continuously"}}],"riktigSvar":"C","forklaring":{"no":"Sikt er begrenset.","th":"ทัศนวิสัยจำกัด","en":"Limited visibility"}},
{"sporsmal":{"no":"Hva er riktig ved bruk av mobil under kjøring?","th":"ใช้มือถือขณะขับควรอย่างไร?","en":"Phone use while driving?"},"alternativer":[{"text":{"no":"Håndholdt er ok","th":"ถือได้","en":"Handheld ok"}},{"text":{"no":"Kun handsfree","th":"แฮนด์ฟรีเท่านั้น","en":"Handsfree only"}},{"text":{"no":"Kun i lav fart","th":"เฉพาะช้า","en":"Only at low speed"}},{"text":{"no":"Aldri lov","th":"ห้ามทั้งหมด","en":"Never allowed"}}],"riktigSvar":"B","forklaring":{"no":"Håndholdt er forbudt.","th":"ห้ามถือ","en":"Handheld is prohibited"}},
{"sporsmal":{"no":"Du kjører på motorvei. Når skal du bruke venstre felt?","th":"มอเตอร์เวย์ควรใช้เลนซ้ายเมื่อใด?","en":"Motorway—when to use left lane?"},"alternativer":[{"text":{"no":"Alltid","th":"เสมอ","en":"Always"}},{"text":{"no":"Ved forbikjøring","th":"เมื่อแซง","en":"When overtaking"}},{"text":{"no":"Ved lav fart","th":"เมื่อช้า","en":"When slow"}},{"text":{"no":"Aldri","th":"ไม่เคย","en":"Never"}}],"riktigSvar":"B","forklaring":{"no":"Hold til høyre ellers.","th":"ปกติชิดขวา","en":"Keep right otherwise"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring gjennom vannplaning (aquaplaning)?","th":"รถเหินน้ำควรทำอย่างไร?","en":"Aquaplaning—what is correct?"},"alternativer":[{"text":{"no":"Bremse hardt","th":"เบรกแรง","en":"Brake hard"}},{"text":{"no":"Slippe gass rolig og holde rett","th":"ผ่อนคันเร่งและควบคุมตรง","en":"Ease off throttle and keep straight"}},{"text":{"no":"Svinge brått","th":"หักพวงมาลัยแรง","en":"Steer sharply"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}}],"riktigSvar":"B","forklaring":{"no":"Gjenopprett grep kontrollert.","th":"คุมรถให้นิ่ง","en":"Regain grip smoothly"}},
{"sporsmal":{"no":"Hva er riktig ved parkering i motbakke?","th":"จอดบนทางขึ้นควรทำอย่างไร?","en":"Parking uphill?"},"alternativer":[{"text":{"no":"Kun håndbrems","th":"เบรกมืออย่างเดียว","en":"Handbrake only"}},{"text":{"no":"Håndbrems + gir og hjul bort fra kant","th":"เบรกมือ+เข้าเกียร์+หันล้อออก","en":"Handbrake + gear + wheels away from curb"}},{"text":{"no":"Fri gir","th":"เกียร์ว่าง","en":"Neutral"}},{"text":{"no":"Ingen tiltak","th":"ไม่ต้องทำ","en":"No action"}}],"riktigSvar":"B","forklaring":{"no":"Sikrer bilen mot rulling.","th":"ป้องกันรถไหล","en":"Prevents rolling"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring nær skole?","th":"ใกล้โรงเรียนควรทำอย่างไร?","en":"Near a school?"},"alternativer":[{"text":{"no":"Holde fartsgrensen uansett","th":"คงความเร็ว","en":"Keep limit regardless"}},{"text":{"no":"Være ekstra oppmerksom og redusere fart","th":"ระวังและลดความเร็ว","en":"Be extra alert and slow down"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}},{"text":{"no":"Kjøre forbi raskt","th":"แซงเร็ว","en":"Pass quickly"}}],"riktigSvar":"B","forklaring":{"no":"Barn er uforutsigbare.","th":"เด็กคาดเดายาก","en":"Children are unpredictable"}},
{"sporsmal":{"no":"Hva er riktig ved møte på smal vei?","th":"ถนนแคบสวนกันควรทำอย่างไร?","en":"Meeting on a narrow road?"},"alternativer":[{"text":{"no":"Kjøre på","th":"ไปต่อ","en":"Continue"}},{"text":{"no":"Tilpasse og gi plass","th":"ปรับและให้ทาง","en":"Adjust and give space"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Vis hensyn.","th":"ให้ทาง","en":"Be considerate"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med tilhenger?","th":"ลากพ่วงควรทำอย่างไร?","en":"Driving with a trailer?"},"alternativer":[{"text":{"no":"Kortere avstand","th":"ระยะสั้น","en":"Shorter distance"}},{"text":{"no":"Lengre avstand og lavere fart","th":"ระยะยาวและช้าลง","en":"Longer distance and lower speed"}},{"text":{"no":"Samme som vanlig","th":"เหมือนเดิม","en":"Same as usual"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Økt bremselengde.","th":"หยุดยากขึ้น","en":"Longer stopping distance"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i mørke uten gatebelysning?","th":"กลางคืนไม่มีไฟถนนควรทำอย่างไร?","en":"Night driving without street lighting?"},"alternativer":[{"text":{"no":"Kun nærlys","th":"ไฟต่ำอย่างเดียว","en":"Low beam only"}},{"text":{"no":"Bruke fjernlys når mulig","th":"ใช้ไฟสูงเมื่อได้","en":"Use high beam when possible"}},{"text":{"no":"Ingen lys","th":"ไม่ใช้ไฟ","en":"No lights"}},{"text":{"no":"Parklys","th":"ไฟจอด","en":"Parking lights"}}],"riktigSvar":"B","forklaring":{"no":"Bedre sikt uten å blende.","th":"มองเห็นดี","en":"Better visibility"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i regn med spor i veien?","th":"ฝนมีร่องน้ำควรทำอย่างไร?","en":"Rain with road grooves?"},"alternativer":[{"text":{"no":"Kjøre i sporene","th":"ขับตามร่อง","en":"Drive in grooves"}},{"text":{"no":"Unngå dype spor der mulig","th":"หลีกเลี่ยงร่องลึก","en":"Avoid deep grooves if possible"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Reduserer vannplaning.","th":"ลดเหินน้ำ","en":"Reduces aquaplaning"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i rundkjøring—plassering før avkjørsel til høyre?","th":"วงเวียนจะออกขวาควรอยู่เลนไหน?","en":"Roundabout—taking the first exit right?"},"alternativer":[{"text":{"no":"Venstre felt","th":"ซ้าย","en":"Left lane"}},{"text":{"no":"Høyre felt","th":"ขวา","en":"Right lane"}},{"text":{"no":"Midten","th":"กลาง","en":"Middle"}},{"text":{"no":"Valgfritt","th":"แล้วแต่","en":"Either"}}],"riktigSvar":"B","forklaring":{"no":"Legg deg til høyre.","th":"ชิดขวา","en":"Use right lane"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i tett tåke med flere felt?","th":"หมอกหนาหลายเลนควรทำอย่างไร?","en":"Dense fog with multiple lanes?"},"alternativer":[{"text":{"no":"Bytte felt ofte","th":"เปลี่ยนเลนบ่อย","en":"Change lanes often"}},{"text":{"no":"Holde felt og redusere fart","th":"อยู่เลนและช้าลง","en":"Keep lane and slow down"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Stabilitet og sikt.","th":"ความนิ่ง","en":"Stability and visibility"}},
{"sporsmal":{"no":"Hva er riktig ved forbikjøring før bakketopp?","th":"จะแซงก่อนขึ้นเนินควรทำอย่างไร?","en":"Overtaking before a crest?"},"alternativer":[{"text":{"no":"Tillatt","th":"อนุญาต","en":"Allowed"}},{"text":{"no":"Unngå – dårlig sikt","th":"หลีกเลี่ยง","en":"Avoid—poor visibility"}},{"text":{"no":"Kun natt","th":"เฉพาะกลางคืน","en":"Night only"}},{"text":{"no":"Kun med horn","th":"ต้องบีบแตร","en":"With horn"}}],"riktigSvar":"B","forklaring":{"no":"Sikt er utilstrekkelig.","th":"มองไม่เห็น","en":"Insufficient sight"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med barn i bilen?","th":"มีเด็กในรถควรทำอย่างไร?","en":"Driving with children?"},"alternativer":[{"text":{"no":"Ingen ekstra tiltak","th":"ไม่ต้องเพิ่ม","en":"No extra measures"}},{"text":{"no":"Sikre barn korrekt og kjøre rolig","th":"ยึดเด็กและขับนุ่มนวล","en":"Secure children and drive smoothly"}},{"text":{"no":"Kjøre fortere","th":"เร็วขึ้น","en":"Drive faster"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Sikkerhet først.","th":"ความปลอดภัย","en":"Safety first"}},
{"sporsmal":{"no":"Hva er riktig ved bruk av nødblink?","th":"ไฟฉุกเฉินใช้เมื่อใด?","en":"Hazard lights—when to use?"},"alternativer":[{"text":{"no":"Når du parkerer kort","th":"จอดสั้น","en":"Short parking"}},{"text":{"no":"Ved fare/stans som hindrer trafikk","th":"เมื่ออันตราย/จอดขวาง","en":"In danger/obstruction"}},{"text":{"no":"Alltid i kø","th":"เสมอในรถติด","en":"Always in jams"}},{"text":{"no":"Aldri","th":"ไม่เคย","en":"Never"}}],"riktigSvar":"B","forklaring":{"no":"Varsle fare.","th":"เตือนอันตราย","en":"Warn others"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i sidevind på bro?","th":"ลมข้างบนสะพานควรทำอย่างไร?","en":"Crosswind on a bridge?"},"alternativer":[{"text":{"no":"Løs hånd på rattet","th":"จับหลวม","en":"Loose grip"}},{"text":{"no":"Fast grep og redusert fart","th":"จับแน่นและช้าลง","en":"Firm grip and slow down"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Bedre kontroll.","th":"ควบคุมได้ดี","en":"Better control"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i mørk tunnel?","th":"อุโมงค์มืดควรทำอย่างไร?","en":"Dark tunnel driving?"},"alternativer":[{"text":{"no":"Ingen lys","th":"ไม่ใช้ไฟ","en":"No lights"}},{"text":{"no":"Bruke nærlys","th":"ใช้ไฟต่ำ","en":"Use low beam"}},{"text":{"no":"Bruke fjernlys hele tiden","th":"ไฟสูงตลอด","en":"High beam always"}},{"text":{"no":"Parklys","th":"ไฟจอด","en":"Parking lights"}}],"riktigSvar":"B","forklaring":{"no":"Unngå blending.","th":"ไม่แยงตา","en":"Avoid dazzling"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring på landevei med dyr langs veien?","th":"ชนบทมีสัตว์ควรทำอย่างไร?","en":"Rural road with animals?"},"alternativer":[{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Redusere fart og være beredt","th":"ลดความเร็วและระวัง","en":"Slow down and be ready"}},{"text":{"no":"Bruke horn kontinuerlig","th":"บีบแตรตลอด","en":"Use horn continuously"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Dyr kan krysse plutselig.","th":"สัตว์อาจวิ่งตัด","en":"Animals may cross suddenly"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med dårlig sikt bakover?","th":"มองหลังไม่ชัดควรทำอย่างไร?","en":"Poor rear visibility?"},"alternativer":[{"text":{"no":"Rygge raskt","th":"ถอยเร็ว","en":"Reverse fast"}},{"text":{"no":"Be om hjelp eller gå ut og se","th":"ขอคนช่วย/ลงไปดู","en":"Ask for help/check outside"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}},{"text":{"no":"Kun speil","th":"ใช้กระจกอย่างเดียว","en":"Mirrors only"}}],"riktigSvar":"B","forklaring":{"no":"Sikre oversikt.","th":"ต้องเห็นชัด","en":"Ensure visibility"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i kryss uten skilt når to biler kommer samtidig?","th":"แยกไม่มีป้าย รถมาพร้อมกันควรทำอย่างไร?","en":"Uncontrolled intersection—two cars arrive together?"},"alternativer":[{"text":{"no":"Den til venstre kjører først","th":"ซ้ายไปก่อน","en":"Left goes first"}},{"text":{"no":"Den til høyre kjører først","th":"ขวาไปก่อน","en":"Right goes first"}},{"text":{"no":"Begge stopper","th":"ทั้งคู่หยุด","en":"Both stop"}},{"text":{"no":"Den raskeste kjører","th":"คันเร็วไป","en":"Faster goes"}}],"riktigSvar":"B","forklaring":{"no":"Høyreregelen.","th":"กฎขวา","en":"Right-hand rule"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i tett trafikk på motorvei?","th":"รถติดบนมอเตอร์เวย์ควรทำอย่างไร?","en":"Heavy traffic on motorway?"},"alternativer":[{"text":{"no":"Bytte felt ofte","th":"เปลี่ยนเลนบ่อย","en":"Change lanes often"}},{"text":{"no":"Holde jevn fart og avstand","th":"ความเร็วคงที่และเว้นระยะ","en":"Keep steady speed and distance"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Flyt og sikkerhet.","th":"ปลอดภัย","en":"Flow and safety"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i mørke med regn?","th":"กลางคืนฝนตกควรทำอย่างไร?","en":"Night driving in rain?"},"alternativer":[{"text":{"no":"Kun fjernlys","th":"ไฟสูง","en":"High beam only"}},{"text":{"no":"Nærlys og redusert fart","th":"ไฟต่ำและช้าลง","en":"Low beam and slow down"}},{"text":{"no":"Ingen lys","th":"ไม่ใช้ไฟ","en":"No lights"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}}],"riktigSvar":"B","forklaring":{"no":"Bedre sikt og grep.","th":"มองเห็นดีขึ้น","en":"Better visibility and grip"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i rundkjøring—bytte felt inne?","th":"เปลี่ยนเลนในวงเวียนควรทำอย่างไร?","en":"Changing lanes inside a roundabout?"},"alternativer":[{"text":{"no":"Tillatt uten tegn","th":"ได้โดยไม่ต้องบอก","en":"Allowed without signal"}},{"text":{"no":"Kun hvis trygt og med tegn","th":"เมื่อปลอดภัยและให้สัญญาณ","en":"Only if safe and with signal"}},{"text":{"no":"Aldri","th":"ไม่เคย","en":"Never"}},{"text":{"no":"Kun natt","th":"เฉพาะกลางคืน","en":"Night only"}}],"riktigSvar":"B","forklaring":{"no":"Speil/blindsone + blink.","th":"ดูจกและไฟเลี้ยว","en":"Mirrors/blind spot + signal"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i motbakke med kø?","th":"ขึ้นเขารถติดควรทำอย่างไร?","en":"Uphill in traffic jam?"},"alternativer":[{"text":{"no":"Rulle bakover","th":"ไหลถอย","en":"Roll back"}},{"text":{"no":"Bruke håndbrems/start-assist","th":"ใช้เบรกมือ/ช่วยออกตัว","en":"Use handbrake/assist"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Unngå rulling bakover.","th":"กันรถไหล","en":"Prevent rollback"}},
]

async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    inserted = 0
    skipped = 0

    for q in RAW:
        existing = await db.questions.find_one({"question.no": q["sporsmal"]["no"]})
        if existing:
            skipped += 1
            continue
        doc = {
            "id": str(uuid.uuid4()),
            "question": q["sporsmal"],
            "options": [{"id": LETTERS[i], "text": q["alternativer"][i]["text"]} for i in range(4)],
            "correctOptionId": q["riktigSvar"],
            "explanation": q["forklaring"],
            "bildeUrl": q.get("bildeUrl") or None,
            "category": "Road Rules",
            "difficulty": "medium",
            "active": True,
            "schema_version": 2,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.questions.insert_one(doc)
        inserted += 1

    print(f"Done! Inserted: {inserted}, Skipped: {skipped}")
    total = await db.questions.count_documents({})
    print(f"Total: {total}")
    client.close()

asyncio.run(seed())
