"""Seed new questions batch mapped to v2 schema."""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid, os
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

LETTERS = ["A", "B", "C", "D"]

RAW = [
{"sporsmal":{"no":"Hva er riktig før du åpner bildøren etter parkering?","th":"ก่อนเปิดประตูรถหลังจอด ควรทำอะไร?","en":"What is correct before opening the car door after parking?"},"alternativer":[{"text":{"no":"Åpne raskt","th":"เปิดเร็ว","en":"Open quickly"}},{"text":{"no":"Sjekke speil og blindsonen","th":"ดูจกและมุมอับ","en":"Check mirrors and blind spot"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Unngå å treffe syklister eller andre trafikanter.","th":"ป้องกันชนจักรยานหรือผู้อื่น","en":"Avoid hitting cyclists or other road users"}},
{"sporsmal":{"no":"Hva er riktig ved møte med gående på smal vei uten fortau?","th":"เจอคนเดินบนถนนแคบไม่มีทางเท้า ควรทำอย่างไร?","en":"Meeting pedestrians on a narrow road without sidewalk?"},"alternativer":[{"text":{"no":"Holde fart","th":"คงความเร็ว","en":"Keep speed"}},{"text":{"no":"Senke fart og gi god plass","th":"ชะลอและเว้นที่","en":"Slow down and give space"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}},{"text":{"no":"Kjøre tett forbi","th":"ขับชิดผ่าน","en":"Pass closely"}}],"riktigSvar":"B","forklaring":{"no":"Gående er myke trafikanter og trenger plass.","th":"คนเดินเปราะบาง ต้องให้พื้นที่","en":"Pedestrians are vulnerable and need space"}},
{"sporsmal":{"no":"Hva er riktig når du kjører ut fra privat eiendom?","th":"ออกจากพื้นที่ส่วนตัวควรทำอย่างไร?","en":"What is correct when driving out from private property?"},"alternativer":[{"text":{"no":"Du har forkjørsrett","th":"คุณมีสิทธิ์ก่อน","en":"You have priority"}},{"text":{"no":"Du har vikeplikt for all trafikk","th":"คุณต้องให้ทางทุกคน","en":"You must yield to all traffic"}},{"text":{"no":"Kun vike for biler","th":"ให้ทางเฉพาะรถยนต์","en":"Yield only to cars"}},{"text":{"no":"Kun vike for fotgjengere","th":"ให้ทางเฉพาะคนเดิน","en":"Yield only to pedestrians"}}],"riktigSvar":"B","forklaring":{"no":"Ved utkjøring fra privat eiendom har du vikeplikt.","th":"ออกจากพื้นที่ส่วนตัวต้องให้ทาง","en":"You must yield when exiting private property"}},
{"sporsmal":{"no":"Hva er riktig om kjøring over gang- og sykkelvei ved utkjøring?","th":"ออกจากทางแล้วตัดผ่านทางเดิน/ทางจักรยานควรทำอย่างไร?","en":"Crossing a pedestrian and cycle path when exiting?"},"alternativer":[{"text":{"no":"Du har forkjørsrett","th":"คุณมีสิทธิ์ก่อน","en":"You have priority"}},{"text":{"no":"Du må vike for gående og syklende","th":"ต้องให้ทางคนเดินและจักรยาน","en":"You must yield to pedestrians and cyclists"}},{"text":{"no":"Kun gående har rett","th":"เฉพาะคนเดิน","en":"Only pedestrians have priority"}},{"text":{"no":"Kun syklister har rett","th":"เฉพาะจักรยาน","en":"Only cyclists have priority"}}],"riktigSvar":"B","forklaring":{"no":"Du må vike for både gående og syklende.","th":"ต้องให้ทางทั้งคนเดินและจักรยาน","en":"You must yield to both pedestrians and cyclists"}},
{"sporsmal":{"no":"Hva er riktig ved stans på motorvei?","th":"หยุดบนมอเตอร์เวย์ได้เมื่อไหร่?","en":"When may you stop on a motorway?"},"alternativer":[{"text":{"no":"Ved telefonsamtale","th":"ตอนรับโทรศัพท์","en":"For a phone call"}},{"text":{"no":"Kun ved nødsituasjon","th":"เฉพาะฉุกเฉิน","en":"Only in an emergency"}},{"text":{"no":"For å sjekke kart","th":"ดูแผนที่","en":"To check the map"}},{"text":{"no":"For å slippe av passasjer","th":"ส่งคนลง","en":"Drop off a passenger"}}],"riktigSvar":"B","forklaring":{"no":"Stans er bare tillatt ved nød.","th":"หยุดได้เฉพาะฉุกเฉิน","en":"Stopping is only allowed in emergencies"}},
{"sporsmal":{"no":"Hva er riktig når dekktrykket er for lavt?","th":"แรงดันลมยางต่ำเกินไปจะเป็นอย่างไร?","en":"What is correct when tire pressure is too low?"},"alternativer":[{"text":{"no":"Bedre styring","th":"บังคับดีขึ้น","en":"Better handling"}},{"text":{"no":"Økt drivstofforbruk og slitasje","th":"กินน้ำมันและสึกมากขึ้น","en":"Higher fuel use and wear"}},{"text":{"no":"Kortere bremselengde","th":"เบรกสั้นลง","en":"Shorter braking distance"}},{"text":{"no":"Ingen betydning","th":"ไม่มีผล","en":"No effect"}}],"riktigSvar":"B","forklaring":{"no":"For lavt dekktrykk gir mer slitasje og forbruk.","th":"ลมยางต่ำทำให้สึกและกินน้ำมัน","en":"Low tire pressure increases wear and fuel use"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring gjennom en skarp sving?","th":"เข้าโค้งแคบควรทำอย่างไร?","en":"Driving through a sharp bend?"},"alternativer":[{"text":{"no":"Bremse hardt midt i svingen","th":"เบรกแรงกลางโค้ง","en":"Brake hard mid-corner"}},{"text":{"no":"Tilpasse fart før svingen","th":"ลดความเร็วก่อนโค้ง","en":"Adjust speed before the bend"}},{"text":{"no":"Gasse på inn i svingen","th":"เร่งเข้าโค้ง","en":"Accelerate into the bend"}},{"text":{"no":"Se rett foran bilen","th":"มองหน้ารถอย่างเดียว","en":"Look only right in front of the car"}}],"riktigSvar":"B","forklaring":{"no":"Riktig fart velges før svingen.","th":"ต้องลดความเร็วก่อนโค้ง","en":"Correct speed is chosen before the bend"}},
{"sporsmal":{"no":"Hva er riktig når du blir forbikjørt?","th":"เมื่อคุณกำลังถูกแซง ควรทำอย่างไร?","en":"What is correct when you are being overtaken?"},"alternativer":[{"text":{"no":"Øke farten","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Holde jevn fart og gi plass","th":"รักษาความเร็วและให้พื้นที่","en":"Keep steady speed and give space"}},{"text":{"no":"Legge deg mot midten","th":"ขับเข้ากลาง","en":"Move toward center"}},{"text":{"no":"Bruke horn","th":"บีบแตร","en":"Use horn"}}],"riktigSvar":"B","forklaring":{"no":"Du skal ikke gjøre forbikjøring vanskeligere.","th":"อย่าทำให้แซงยาก","en":"Do not make overtaking harder"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring nær et ulykkessted?","th":"ใกล้จุดอุบัติเหตุควรทำอย่างไร?","en":"Near an accident scene?"},"alternativer":[{"text":{"no":"Kjøre sakte og vise hensyn","th":"ชะลอและระวัง","en":"Slow down and be considerate"}},{"text":{"no":"Filme med mobilen","th":"ถ่ายวิดีโอ","en":"Film with your phone"}},{"text":{"no":"Kjøre raskt forbi","th":"รีบผ่าน","en":"Pass quickly"}},{"text":{"no":"Bruke horn for å få plass","th":"บีบแตรเอาทาง","en":"Use horn to get through"}}],"riktigSvar":"A","forklaring":{"no":"Vis hensyn og unngå nye farer.","th":"ระวังและไม่สร้างอันตรายเพิ่ม","en":"Be considerate and avoid creating more danger"}},
{"sporsmal":{"no":"Hva er riktig når du ser barn leke nær veien?","th":"เห็นเด็กเล่นใกล้ถนนควรทำอย่างไร?","en":"When you see children playing near the road?"},"alternativer":[{"text":{"no":"Holde fartsgrensen hvis du vil","th":"วิ่งตามป้าย","en":"Keep the speed limit"}},{"text":{"no":"Senke fart og være klar til å stoppe","th":"ลดความเร็วและพร้อมหยุด","en":"Slow down and be ready to stop"}},{"text":{"no":"Bruke horn for å varsle","th":"บีบแตรเตือน","en":"Use horn to warn"}},{"text":{"no":"Ignorere dem","th":"ไม่สนใจ","en":"Ignore them"}}],"riktigSvar":"B","forklaring":{"no":"Barn kan være uforutsigbare.","th":"เด็กคาดเดายาก","en":"Children can be unpredictable"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i mørke og regn på landevei?","th":"ขับกลางคืนฝนตกบนถนนชนบทควรทำอย่างไร?","en":"Night driving in rain on a rural road?"},"alternativer":[{"text":{"no":"Kun fjernlys","th":"ไฟสูงอย่างเดียว","en":"High beam only"}},{"text":{"no":"Nærlys, lavere fart og større avstand","th":"ไฟต่ำ ช้าลง เว้นระยะ","en":"Low beam, lower speed, more distance"}},{"text":{"no":"Ingen lys","th":"ไม่ใช้ไฟ","en":"No lights"}},{"text":{"no":"Samme fart som i tørt vær","th":"ความเร็วเท่าเดิม","en":"Same speed as in dry weather"}}],"riktigSvar":"B","forklaring":{"no":"Mørke og regn krever mer margin.","th":"ต้องเผื่อระยะมากขึ้น","en":"Dark and rain require more safety margin"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring mot lav sol?","th":"ขับสวนแดดต่ำควรทำอย่างไร?","en":"Driving into low sun?"},"alternativer":[{"text":{"no":"Bruke solskjerm/solbriller og senke fart","th":"ใช้แผงกันแดด/แว่นและชะลอ","en":"Use visor/sunglasses and slow down"}},{"text":{"no":"Øke fart for å komme fort forbi","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Se rett i solen","th":"มองตรงไปที่แดด","en":"Look directly at the sun"}},{"text":{"no":"Slå av lysene","th":"ปิดไฟ","en":"Turn off lights"}}],"riktigSvar":"A","forklaring":{"no":"Lav sol reduserer sikten.","th":"แดดต่ำทำให้มองยาก","en":"Low sun reduces visibility"}},
{"sporsmal":{"no":"Hva er riktig ved felt som opphører?","th":"เลนที่กำลังสิ้นสุดควรทำอย่างไร?","en":"When your lane is ending?"},"alternativer":[{"text":{"no":"Den i feltet som opphører må tilpasse seg","th":"เลนที่สิ้นสุดต้องปรับตัว","en":"The ending lane must merge responsibly"}},{"text":{"no":"De andre må alltid stoppe","th":"คนอื่นต้องหยุด","en":"Others must always stop"}},{"text":{"no":"Du har alltid forkjørsrett","th":"คุณมาก่อนเสมอ","en":"You always have priority"}},{"text":{"no":"Bruk horn og press deg inn","th":"บีบแตรแล้วแทรก","en":"Use horn and force in"}}],"riktigSvar":"A","forklaring":{"no":"Du må tilpasse deg trafikken i feltet ved siden av.","th":"ต้องปรับตัวเข้าการจราจร","en":"You must adapt to adjacent traffic"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring over jernbaneovergang uten bom?","th":"ทางรถไฟไม่มีไม้กั้นควรทำอย่างไร?","en":"Railway crossing without barriers?"},"alternativer":[{"text":{"no":"Kjøre raskt over","th":"รีบข้าม","en":"Cross quickly"}},{"text":{"no":"Være ekstra oppmerksom og sikre at det er klart","th":"ระวังและดูให้ชัด","en":"Be extra cautious and make sure it is clear"}},{"text":{"no":"Stanse på sporet hvis usikker","th":"หยุดบนรางถ้าไม่แน่ใจ","en":"Stop on the tracks if unsure"}},{"text":{"no":"Ignorere skilt","th":"ไม่สนใจป้าย","en":"Ignore signs"}}],"riktigSvar":"B","forklaring":{"no":"Jernbane krever ekstra aktsomhet.","th":"ต้องระวังมาก","en":"Railway crossings require extra caution"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med last på taket?","th":"บรรทุกของบนหลังคาควรทำอย่างไร?","en":"Driving with roof load?"},"alternativer":[{"text":{"no":"Kjøre som vanlig","th":"ขับเหมือนเดิม","en":"Drive as normal"}},{"text":{"no":"Være obs på endret stabilitet","th":"ระวังความมั่นคงเปลี่ยน","en":"Be aware of changed stability"}},{"text":{"no":"Øke fart på motorvei","th":"เพิ่มความเร็วบนมอเตอร์เวย์","en":"Increase speed on motorway"}},{"text":{"no":"Ignorere vinden","th":"ไม่สนใจลม","en":"Ignore wind"}}],"riktigSvar":"B","forklaring":{"no":"Last på taket påvirker stabiliteten.","th":"ของบนหลังคามีผลต่อการทรงตัว","en":"Roof load affects stability"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med dårlig sikt framover?","th":"มองไปข้างหน้าไม่ชัดควรทำอย่างไร?","en":"Poor forward visibility?"},"alternativer":[{"text":{"no":"Øke fart for å komme gjennom","th":"เพิ่มความเร็ว","en":"Increase speed"}},{"text":{"no":"Senke fart og være klar til å stoppe","th":"ลดความเร็วและพร้อมหยุด","en":"Reduce speed and be ready to stop"}},{"text":{"no":"Kjøre etter følelsen","th":"ขับตามความรู้สึก","en":"Drive by feel"}},{"text":{"no":"Bruke horn hele tiden","th":"บีบแตรตลอด","en":"Use horn continuously"}}],"riktigSvar":"B","forklaring":{"no":"Dårlig sikt krever lavere fart.","th":"มองไม่ชัดต้องช้าลง","en":"Poor visibility requires lower speed"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring forbi parkert bilrekke?","th":"ขับผ่านรถจอดเรียงควรทำอย่างไร?","en":"Passing a row of parked cars?"},"alternativer":[{"text":{"no":"Holde høy fart","th":"เร็ว","en":"Keep high speed"}},{"text":{"no":"Være klar for at noen kan åpne dør eller gå ut","th":"พร้อมเผื่อมีคนเปิดประตู/เดินออก","en":"Be ready for doors opening or people stepping out"}},{"text":{"no":"Kjøre helt inntil","th":"ชิดมาก","en":"Drive very close"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Det kan oppstå plutselige farer.","th":"อาจมีอันตรายฉับพลัน","en":"Sudden hazards can occur"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring i kraftig sidevind med tilhenger?","th":"ลมข้างแรงพร้อมรถพ่วงควรทำอย่างไร?","en":"Strong crosswind with trailer?"},"alternativer":[{"text":{"no":"Senke fart og holde godt i rattet","th":"ลดความเร็วและจับพวงมาลัยแน่น","en":"Slow down and hold the wheel firmly"}},{"text":{"no":"Øke fart for stabilitet","th":"เพิ่มความเร็ว","en":"Increase speed for stability"}},{"text":{"no":"Slippe rattet litt","th":"ปล่อยพวงมาลัย","en":"Loosen your grip"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"A","forklaring":{"no":"Tilhenger påvirkes lett av sidevind.","th":"รถพ่วงโดนลมข้างง่าย","en":"Trailers are easily affected by crosswind"}},
{"sporsmal":{"no":"Hva er riktig ved møte med hest i veien?","th":"เจอม้าบนถนนควรทำอย่างไร?","en":"Meeting a horse on the road?"},"alternativer":[{"text":{"no":"Kjøre tett forbi","th":"ขับชิดผ่าน","en":"Pass closely"}},{"text":{"no":"Senke fart og kjøre rolig forbi","th":"ชะลอและผ่านอย่างนุ่มนวล","en":"Slow down and pass calmly"}},{"text":{"no":"Bruke horn for å varsle","th":"บีบแตรเตือน","en":"Use horn to warn"}},{"text":{"no":"Øke fart","th":"เพิ่มความเร็ว","en":"Increase speed"}}],"riktigSvar":"B","forklaring":{"no":"Hester kan bli skremt.","th":"ม้าอาจตกใจ","en":"Horses can be startled"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring nær trikk?","th":"ใกล้รถรางควรทำอย่างไร?","en":"Driving near a tram?"},"alternativer":[{"text":{"no":"Forvente at den kan svinge annerledes enn bil","th":"คาดว่ามันเลี้ยวต่างจากรถ","en":"Expect it may move differently from cars"}},{"text":{"no":"Press deg forbi","th":"แทรกผ่าน","en":"Force past it"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}},{"text":{"no":"Stoppe på skinnene","th":"หยุดบนราง","en":"Stop on tracks"}}],"riktigSvar":"A","forklaring":{"no":"Trikk følger spor og kan ha annen bevegelse.","th":"รถรางวิ่งตามราง","en":"A tram follows tracks and moves differently"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring når du er trøtt?","th":"เมื่อคุณง่วงควรทำอย่างไร?","en":"What is correct when you are tired?"},"alternativer":[{"text":{"no":"Åpne vinduet og kjøre videre","th":"เปิดหน้าต่างแล้วขับต่อ","en":"Open the window and keep driving"}},{"text":{"no":"Ta pause eller la være å kjøre","th":"พักหรือไม่ขับ","en":"Take a break or do not drive"}},{"text":{"no":"Drikke kaffe og kjøre fortere","th":"ดื่มกาแฟแล้วเร็วขึ้น","en":"Drink coffee and drive faster"}},{"text":{"no":"Ignorere det","th":"ไม่สนใจ","en":"Ignore it"}}],"riktigSvar":"B","forklaring":{"no":"Trøtthet er farlig i trafikken.","th":"ง่วงอันตราย","en":"Fatigue is dangerous"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring med nedsatt sikt på grunn av skitne ruter?","th":"กระจกสกปรกทำให้มองไม่ชัดควรทำอย่างไร?","en":"Reduced visibility due to dirty windows?"},"alternativer":[{"text":{"no":"Kjøre som normalt","th":"ขับปกติ","en":"Drive normally"}},{"text":{"no":"Rengjøre rutene før kjøring","th":"เช็ดกระจกก่อนขับ","en":"Clean the windows before driving"}},{"text":{"no":"Bare bruke viskere","th":"ใช้ที่ปัดอย่างเดียว","en":"Use wipers only"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"God sikt er grunnleggende.","th":"ต้องมองเห็นชัด","en":"Good visibility is essential"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring gjennom et område med veiarbeid?","th":"ผ่านเขตก่อสร้างถนนควรทำอย่างไร?","en":"Driving through roadworks?"},"alternativer":[{"text":{"no":"Følge midlertidig skilting","th":"ตามป้ายชั่วคราว","en":"Follow temporary signs"}},{"text":{"no":"Følge gamle vaner","th":"ทำเหมือนเดิม","en":"Follow old habits"}},{"text":{"no":"Ignorere gule skilt","th":"ไม่สนใจป้ายเหลือง","en":"Ignore yellow signs"}},{"text":{"no":"Øke fart forbi","th":"รีบผ่าน","en":"Speed through"}}],"riktigSvar":"A","forklaring":{"no":"Midlertidig skilting gjelder.","th":"ป้ายชั่วคราวมีผล","en":"Temporary signs apply"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring på vei med mange myke trafikanter?","th":"ถนนมีคนเดิน/จักรยานมากควรทำอย่างไร?","en":"Road with many vulnerable road users?"},"alternativer":[{"text":{"no":"Senke fart og være ekstra oppmerksom","th":"ชะลอและระวังมาก","en":"Slow down and be extra alert"}},{"text":{"no":"Holde vanlig fart","th":"ความเร็วปกติ","en":"Keep normal speed"}},{"text":{"no":"Bruke horn ofte","th":"บีบแตรบ่อย","en":"Use horn often"}},{"text":{"no":"Kjøre tett forbi","th":"ขับชิดผ่าน","en":"Pass closely"}}],"riktigSvar":"A","forklaring":{"no":"Myke trafikanter krever ekstra hensyn.","th":"ต้องระวังผู้ใช้ถนนเปราะบาง","en":"Vulnerable users require extra caution"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring når veien smalner?","th":"ถนนแคบลงควรทำอย่างไร?","en":"When the road narrows?"},"alternativer":[{"text":{"no":"Holde samme posisjon og fart","th":"คงตำแหน่งและความเร็ว","en":"Keep same position and speed"}},{"text":{"no":"Tilpasse fart og plassering","th":"ปรับความเร็วและตำแหน่ง","en":"Adapt speed and position"}},{"text":{"no":"Øke fart for å komme først","th":"เพิ่มความเร็ว","en":"Increase speed to get first"}},{"text":{"no":"Ignorere","th":"ไม่สนใจ","en":"Ignore"}}],"riktigSvar":"B","forklaring":{"no":"Tilpass deg den smalere veien.","th":"ต้องปรับตัว","en":"Adapt to the narrower road"}},
{"sporsmal":{"no":"Hva er riktig ved kjøring etter mørkets frembrudd?","th":"หลังมืดค่ำควรทำอย่างไร?","en":"After dark—what is correct?"},"alternativer":[{"text":{"no":"Sjekke at alle lys virker","th":"เช็คไฟทั้งหมด","en":"Check all lights work"}},{"text":{"no":"Ignorere lysene","th":"ไม่สนใจไฟ","en":"Ignore lights"}},{"text":{"no":"Kun bruke parklys","th":"ใช้ไฟจอดอย่างเดียว","en":"Use parking lights only"}},{"text":{"no":"Kjøre uten lys i byen","th":"ขับไม่เปิดไฟในเมือง","en":"Drive without lights in city"}}],"riktigSvar":"A","forklaring":{"no":"Lys er viktig for å se og bli sett.","th":"ไฟสำคัญมาก","en":"Lights are important to see and be seen"}},
]

async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    inserted = 0
    skipped = 0

    for q in RAW:
        existing = await db.questions.find_one({"question.no": q["sporsmal"]["no"]})
        if existing:
            skipped += 1
            continue
        doc = {
            "id": str(uuid.uuid4()),
            "question": q["sporsmal"],
            "options": [{"id": LETTERS[i], "text": q["alternativer"][i]["text"]} for i in range(4)],
            "correctOptionId": q["riktigSvar"],
            "explanation": q["forklaring"],
            "bildeUrl": q.get("bildeUrl") or None,
            "category": "Road Rules",
            "difficulty": "medium",
            "active": True,
            "schema_version": 2,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.questions.insert_one(doc)
        inserted += 1

    print(f"Done! Inserted: {inserted}, Skipped: {skipped}")
    total = await db.questions.count_documents({})
    print(f"Total: {total}")
    client.close()

asyncio.run(seed())
