"""Seed 30 new quiz questions into MongoDB."""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid, os
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

NEW_QUESTIONS = [
    # ===== BATCH 1: 10 questions =====
    {
        "question_text_no": "Hva betyr begrepet kjøredyktighet?",
        "question_text_th": "คำว่า 'ความสามารถในการขับขี่' หมายถึงอะไร?",
        "question_text_en": "What does the term 'driving competence' mean?",
        "answer_a_no": "Å kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Driving fast",
        "answer_b_no": "Å kontrollere bilen og ta gode valg", "answer_b_th": "ควบคุมรถและตัดสินใจได้ดี", "answer_b_en": "Controlling the car and making good decisions",
        "answer_c_no": "Å ha ny bil", "answer_c_th": "มีรถใหม่", "answer_c_en": "Having a new car",
        "answer_d_no": "Følge GPS", "answer_d_th": "ตาม GPS", "answer_d_en": "Following GPS",
        "correct_answer": "B",
        "explanation_no": "Kjøredyktighet handler om ferdigheter og gode vurderinger i trafikken.",
        "explanation_th": "คือความสามารถในการควบคุมรถและตัดสินใจในจราจร",
        "explanation_en": "Driving competence is about skills and good judgment in traffic.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hvordan får du best oversikt i trafikken?",
        "question_text_th": "คุณจะมองเห็นสถานการณ์จราจรได้ดีที่สุดอย่างไร?",
        "question_text_en": "How do you get the best overview in traffic?",
        "answer_a_no": "Se rett frem", "answer_a_th": "มองตรงไปข้างหน้า", "answer_a_en": "Look straight ahead",
        "answer_b_no": "Se langt frem og bevege blikket", "answer_b_th": "มองไกลและกวาดสายตา", "answer_b_en": "Look far ahead and move your gaze",
        "answer_c_no": "Se på bilen foran", "answer_c_th": "มองรถคันหน้า", "answer_c_en": "Look at the car ahead",
        "answer_d_no": "Kjøre sakte", "answer_d_th": "ขับช้า", "answer_d_en": "Drive slowly",
        "correct_answer": "B",
        "explanation_no": "Du må bruke blikket aktivt for å oppdage farer tidlig.",
        "explanation_th": "ต้องใช้สายตามองรอบๆ เพื่อเห็นอันตรายล่วงหน้า",
        "explanation_en": "You must actively use your eyes to detect hazards early.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva betyr vikeplikt?",
        "question_text_th": "การให้ทางหมายถึงอะไร?",
        "question_text_en": "What does 'right of way obligation' mean?",
        "answer_a_no": "Kjøre først", "answer_a_th": "ขับไปก่อน", "answer_a_en": "Drive first",
        "answer_b_no": "Stoppe alltid", "answer_b_th": "หยุดเสมอ", "answer_b_en": "Always stop",
        "answer_c_no": "La andre kjøre først", "answer_c_th": "ให้รถคันอื่นผ่านไปก่อน", "answer_c_en": "Let others drive first",
        "answer_d_no": "Blinke", "answer_d_th": "เปิดไฟเลี้ยว", "answer_d_en": "Use turn signal",
        "correct_answer": "C",
        "explanation_no": "Du må gi fri vei til andre trafikanter.",
        "explanation_th": "ต้องให้รถคันอื่นผ่านไปก่อน",
        "explanation_en": "You must give way to other road users.",
        "category": "Right of Way", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er riktig fart?",
        "question_text_th": "ความเร็วที่ถูกต้องคืออะไร?",
        "question_text_en": "What is the correct speed?",
        "answer_a_no": "Alltid maks fart", "answer_a_th": "ขับเร็วสุดเสมอ", "answer_a_en": "Always max speed",
        "answer_b_no": "Tilpasse etter forhold", "answer_b_th": "ปรับตามสถานการณ์", "answer_b_en": "Adapt to conditions",
        "answer_c_no": "Kjøre sakte", "answer_c_th": "ขับช้า", "answer_c_en": "Drive slowly",
        "answer_d_no": "Følge andre", "answer_d_th": "ตามคนอื่น", "answer_d_en": "Follow others",
        "correct_answer": "B",
        "explanation_no": "Farten må tilpasses vei, vær og trafikk.",
        "explanation_th": "ต้องปรับตามสภาพถนน อากาศ และการจราจร",
        "explanation_en": "Speed must be adapted to road, weather and traffic conditions.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva skjer når farten øker?",
        "question_text_th": "เกิดอะไรขึ้นเมื่อความเร็วเพิ่มขึ้น?",
        "question_text_en": "What happens when speed increases?",
        "answer_a_no": "Stopper raskere", "answer_a_th": "หยุดเร็วขึ้น", "answer_a_en": "Stops faster",
        "answer_b_no": "Lengre bremselengde", "answer_b_th": "ระยะเบรกยาวขึ้น", "answer_b_en": "Longer braking distance",
        "answer_c_no": "Bedre kontroll", "answer_c_th": "ควบคุมได้ดีขึ้น", "answer_c_en": "Better control",
        "answer_d_no": "Ingen forskjell", "answer_d_th": "ไม่มีความแตกต่าง", "answer_d_en": "No difference",
        "correct_answer": "B",
        "explanation_no": "Høy fart gir lengre bremselengde og større risiko.",
        "explanation_th": "ยิ่งเร็ว ระยะเบรกยิ่งยาว",
        "explanation_en": "Higher speed means longer braking distance and greater risk.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hvorfor må vi ha fartsgrenser?",
        "question_text_th": "ทำไมต้องมีการจำกัดความเร็ว?",
        "question_text_en": "Why do we need speed limits?",
        "answer_a_no": "For å tjene penger", "answer_a_th": "เพื่อหาเงิน", "answer_a_en": "To make money",
        "answer_b_no": "For å gjøre kjøring vanskelig", "answer_b_th": "เพื่อทำให้ขับยาก", "answer_b_en": "To make driving difficult",
        "answer_c_no": "For å redusere risiko og ulykker", "answer_c_th": "เพื่อลดอุบัติเหตุ", "answer_c_en": "To reduce risk and accidents",
        "answer_d_no": "For å kontrollere biler", "answer_d_th": "เพื่อควบคุมรถ", "answer_d_en": "To control cars",
        "correct_answer": "C",
        "explanation_no": "Fartsgrenser reduserer ulykker og øker sikkerhet.",
        "explanation_th": "การจำกัดความเร็วช่วยลดอุบัติเหตุ",
        "explanation_en": "Speed limits reduce accidents and increase safety.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig i kryss?",
        "question_text_th": "อะไรสำคัญที่สี่แยก?",
        "question_text_en": "What is important at intersections?",
        "answer_a_no": "Kun se frem", "answer_a_th": "มองข้างหน้าเท่านั้น", "answer_a_en": "Only look ahead",
        "answer_b_no": "Kjøre fort", "answer_b_th": "ขับเร็ว", "answer_b_en": "Drive fast",
        "answer_c_no": "Følge vikeplikt og ha oversikt", "answer_c_th": "ให้ทางและมองรอบๆ", "answer_c_en": "Follow right of way and have overview",
        "answer_d_no": "Blinke sent", "answer_d_th": "เปิดไฟเลี้ยวช้า", "answer_d_en": "Signal late",
        "correct_answer": "C",
        "explanation_no": "Du må følge regler og ha god oversikt.",
        "explanation_th": "ต้องให้ทางและมองรอบๆ",
        "explanation_en": "You must follow rules and have a good overview.",
        "category": "Right of Way", "difficulty": "medium",
    },
    {
        "question_text_no": "Hva er vanlig årsak til ulykker?",
        "question_text_th": "สาเหตุทั่วไปของอุบัติเหตุคืออะไร?",
        "question_text_en": "What is a common cause of accidents?",
        "answer_a_no": "Nye biler", "answer_a_th": "รถใหม่", "answer_a_en": "New cars",
        "answer_b_no": "Dårlig vær", "answer_b_th": "สภาพอากาศเลว", "answer_b_en": "Bad weather",
        "answer_c_no": "Menneskelige feil", "answer_c_th": "ข้อผิดพลาดของมนุษย์", "answer_c_en": "Human error",
        "answer_d_no": "Trafikkskilt", "answer_d_th": "ป้ายจราจร", "answer_d_en": "Traffic signs",
        "correct_answer": "C",
        "explanation_no": "De fleste ulykker skyldes menneskelige feil.",
        "explanation_th": "อุบัติเหตุส่วนใหญ่เกิดจากมนุษย์",
        "explanation_en": "Most accidents are caused by human error.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva betyr aktpågivende?",
        "question_text_th": "คำว่า 'ระมัดระวัง' หมายถึงอะไร?",
        "question_text_en": "What does 'attentive' mean?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Være oppmerksom", "answer_b_th": "มีสมาธิและระวัง", "answer_b_en": "Be attentive",
        "answer_c_no": "Kjøre sakte", "answer_c_th": "ขับช้า", "answer_c_en": "Drive slowly",
        "answer_d_no": "Bruke GPS", "answer_d_th": "ใช้ GPS", "answer_d_en": "Use GPS",
        "correct_answer": "B",
        "explanation_no": "Du må være oppmerksom i trafikken.",
        "explanation_th": "ต้องมีสมาธิและระวัง",
        "explanation_en": "You must be attentive in traffic.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva gir god trafikkflyt?",
        "question_text_th": "อะไรทำให้จราจรลื่นไหล?",
        "question_text_en": "What provides good traffic flow?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Kjøre alene", "answer_b_th": "ขับคนเดียว", "answer_b_en": "Drive alone",
        "answer_c_no": "Samarbeid og regler", "answer_c_th": "ร่วมมือและปฏิบัติตามกฎ", "answer_c_en": "Cooperation and rules",
        "answer_d_no": "Ignorere andre", "answer_d_th": "ไม่สนใจคนอื่น", "answer_d_en": "Ignore others",
        "correct_answer": "C",
        "explanation_no": "Samarbeid og regler gir god flyt.",
        "explanation_th": "การร่วมมือช่วยให้จราจรดีขึ้น",
        "explanation_en": "Cooperation and rules provide good traffic flow.",
        "category": "Road Rules", "difficulty": "easy",
    },
    # ===== BATCH 2: 20 questions =====
    {
        "question_text_no": "Hva betyr det å ha god sikt?",
        "question_text_th": "การมองเห็นที่ดีหมายถึงอะไร?",
        "question_text_en": "What does having good visibility mean?",
        "answer_a_no": "Se kun rett frem", "answer_a_th": "มองตรงเท่านั้น", "answer_a_en": "Only look straight ahead",
        "answer_b_no": "Se langt frem og rundt", "answer_b_th": "มองไกลและรอบๆ", "answer_b_en": "Look far ahead and around",
        "answer_c_no": "Se på mobilen", "answer_c_th": "ดูมือถือ", "answer_c_en": "Look at the phone",
        "answer_d_no": "Se i speilet", "answer_d_th": "ดูกระจก", "answer_d_en": "Look in the mirror",
        "correct_answer": "B",
        "explanation_no": "God sikt betyr å ha oversikt i alle retninger.",
        "explanation_th": "การมองเห็นที่ดีคือการมองรอบๆ และไกล",
        "explanation_en": "Good visibility means having overview in all directions.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva bør du gjøre før du svinger?",
        "question_text_th": "คุณควรทำอะไรก่อนเลี้ยว?",
        "question_text_en": "What should you do before turning?",
        "answer_a_no": "Øke farten", "answer_a_th": "เพิ่มความเร็ว", "answer_a_en": "Increase speed",
        "answer_b_no": "Se i speil og blinke", "answer_b_th": "ดูกระจกและเปิดไฟเลี้ยว", "answer_b_en": "Check mirrors and signal",
        "answer_c_no": "Kjøre rett frem", "answer_c_th": "ขับตรงไป", "answer_c_en": "Drive straight",
        "answer_d_no": "Stoppe alltid", "answer_d_th": "หยุดเสมอ", "answer_d_en": "Always stop",
        "correct_answer": "B",
        "explanation_no": "Du må varsle og sjekke trafikken.",
        "explanation_th": "ต้องดูและเปิดไฟเลี้ยวก่อนเลี้ยว",
        "explanation_en": "You must signal and check traffic before turning.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig ved kjøring i mørket?",
        "question_text_th": "อะไรสำคัญเมื่อขับรถตอนกลางคืน?",
        "question_text_en": "What is important when driving in the dark?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Bruke riktig lys", "answer_b_th": "ใช้ไฟให้ถูกต้อง", "answer_b_en": "Use correct lights",
        "answer_c_no": "Kjøre uten lys", "answer_c_th": "ขับไม่เปิดไฟ", "answer_c_en": "Drive without lights",
        "answer_d_no": "Ignorere skilt", "answer_d_th": "ไม่สนใจป้าย", "answer_d_en": "Ignore signs",
        "correct_answer": "B",
        "explanation_no": "Riktig lys gir bedre sikt og sikkerhet.",
        "explanation_th": "ใช้ไฟให้ถูกต้องเพื่อความปลอดภัย",
        "explanation_en": "Correct lighting provides better visibility and safety.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er en sikkerhetsavstand?",
        "question_text_th": "ระยะปลอดภัยคืออะไร?",
        "question_text_en": "What is a safety distance?",
        "answer_a_no": "Avstand til parkerte biler", "answer_a_th": "ระยะห่างจากรถจอด", "answer_a_en": "Distance to parked cars",
        "answer_b_no": "Avstand til bilen foran", "answer_b_th": "ระยะห่างจากรถคันหน้า", "answer_b_en": "Distance to the car ahead",
        "answer_c_no": "Avstand til skilt", "answer_c_th": "ระยะห่างจากป้าย", "answer_c_en": "Distance to signs",
        "answer_d_no": "Avstand til vei", "answer_d_th": "ระยะห่างจากถนน", "answer_d_en": "Distance to road",
        "correct_answer": "B",
        "explanation_no": "Du må ha nok avstand til bilen foran.",
        "explanation_th": "ต้องเว้นระยะห่างจากรถคันหน้า",
        "explanation_en": "You must keep enough distance from the car ahead.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva gjør du ved glatt vei?",
        "question_text_th": "คุณทำอย่างไรเมื่อถนนลื่น?",
        "question_text_en": "What do you do on a slippery road?",
        "answer_a_no": "Kjører fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Øker avstand og senker fart", "answer_b_th": "เพิ่มระยะห่างและลดความเร็ว", "answer_b_en": "Increase distance and reduce speed",
        "answer_c_no": "Bremser hardt", "answer_c_th": "เบรกแรง", "answer_c_en": "Brake hard",
        "answer_d_no": "Ignorerer det", "answer_d_th": "ไม่สนใจ", "answer_d_en": "Ignore it",
        "correct_answer": "B",
        "explanation_no": "Lav fart og avstand gir bedre kontroll.",
        "explanation_th": "ลดความเร็วและเพิ่มระยะห่าง",
        "explanation_en": "Low speed and distance provide better control.",
        "category": "Safety", "difficulty": "medium",
    },
    {
        "question_text_no": "Hva betyr gult lys?",
        "question_text_th": "ไฟเหลืองหมายถึงอะไร?",
        "question_text_en": "What does yellow light mean?",
        "answer_a_no": "Kjør fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Stopp hvis mulig", "answer_b_th": "หยุดถ้าทำได้", "answer_b_en": "Stop if possible",
        "answer_c_no": "Ignorer", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Sving", "answer_d_th": "เลี้ยว", "answer_d_en": "Turn",
        "correct_answer": "B",
        "explanation_no": "Du skal stoppe hvis det er trygt.",
        "explanation_th": "ต้องหยุดถ้าทำได้อย่างปลอดภัย",
        "explanation_en": "You should stop if it is safe to do so.",
        "category": "Traffic Signs", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig ved forbikjøring?",
        "question_text_th": "อะไรสำคัญเมื่อแซง?",
        "question_text_en": "What is important when overtaking?",
        "answer_a_no": "Kjøre fort uten å se", "answer_a_th": "ขับเร็วโดยไม่มอง", "answer_a_en": "Drive fast without looking",
        "answer_b_no": "Ha god oversikt", "answer_b_th": "มองให้ดี", "answer_b_en": "Have a good overview",
        "answer_c_no": "Ikke blinke", "answer_c_th": "ไม่เปิดไฟเลี้ยว", "answer_c_en": "Don't signal",
        "answer_d_no": "Stoppe", "answer_d_th": "หยุด", "answer_d_en": "Stop",
        "correct_answer": "B",
        "explanation_no": "Du må være sikker før du kjører forbi.",
        "explanation_th": "ต้องมั่นใจก่อนแซง",
        "explanation_en": "You must be sure before overtaking.",
        "category": "Road Rules", "difficulty": "medium",
    },
    {
        "question_text_no": "Hva betyr stoppskilt?",
        "question_text_th": "ป้ายหยุดหมายถึงอะไร?",
        "question_text_en": "What does a stop sign mean?",
        "answer_a_no": "Kjøre sakte", "answer_a_th": "ขับช้า", "answer_a_en": "Drive slowly",
        "answer_b_no": "Stoppe helt", "answer_b_th": "หยุดรถสนิท", "answer_b_en": "Stop completely",
        "answer_c_no": "Blinke", "answer_c_th": "เปิดไฟเลี้ยว", "answer_c_en": "Signal",
        "answer_d_no": "Ignorere", "answer_d_th": "ไม่สนใจ", "answer_d_en": "Ignore",
        "correct_answer": "B",
        "explanation_no": "Du må stoppe helt opp.",
        "explanation_th": "ต้องหยุดรถสนิท",
        "explanation_en": "You must come to a complete stop.",
        "category": "Traffic Signs", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig i rundkjøring?",
        "question_text_th": "อะไรสำคัญในวงเวียน?",
        "question_text_en": "What is important in a roundabout?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Følge vikeplikt", "answer_b_th": "ให้ทางรถในวงเวียน", "answer_b_en": "Follow right of way",
        "answer_c_no": "Stoppe alltid", "answer_c_th": "หยุดเสมอ", "answer_c_en": "Always stop",
        "answer_d_no": "Ignorere andre", "answer_d_th": "ไม่สนใจคนอื่น", "answer_d_en": "Ignore others",
        "correct_answer": "B",
        "explanation_no": "Du må gi vei til trafikk i rundkjøringen.",
        "explanation_th": "ต้องให้ทางรถในวงเวียน",
        "explanation_en": "You must yield to traffic in the roundabout.",
        "category": "Right of Way", "difficulty": "medium",
    },
    {
        "question_text_no": "Hva er riktig plassering i vei?",
        "question_text_th": "ตำแหน่งที่ถูกต้องบนถนนคืออะไร?",
        "question_text_en": "What is the correct lane position?",
        "answer_a_no": "Midt i veien", "answer_a_th": "กลางถนน", "answer_a_en": "Middle of the road",
        "answer_b_no": "Høyre side", "answer_b_th": "ด้านขวา", "answer_b_en": "Right side",
        "answer_c_no": "Venstre side", "answer_c_th": "ด้านซ้าย", "answer_c_en": "Left side",
        "answer_d_no": "Hvor som helst", "answer_d_th": "ที่ไหนก็ได้", "answer_d_en": "Anywhere",
        "correct_answer": "B",
        "explanation_no": "Du skal holde høyre side.",
        "explanation_th": "ต้องขับด้านขวา",
        "explanation_en": "You should keep to the right side.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva gjør du ved fotgjengerfelt?",
        "question_text_th": "คุณทำอย่างไรที่ทางม้าลาย?",
        "question_text_en": "What do you do at a pedestrian crossing?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Stoppe for gående", "answer_b_th": "หยุดให้คนข้าม", "answer_b_en": "Stop for pedestrians",
        "answer_c_no": "Ignorere", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Blinke", "answer_d_th": "เปิดไฟเลี้ยว", "answer_d_en": "Signal",
        "correct_answer": "B",
        "explanation_no": "Du må slippe gående over.",
        "explanation_th": "ต้องหยุดให้คนข้าม",
        "explanation_en": "You must let pedestrians cross.",
        "category": "Right of Way", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva betyr grønt lys?",
        "question_text_th": "ไฟเขียวหมายถึงอะไร?",
        "question_text_en": "What does green light mean?",
        "answer_a_no": "Stoppe", "answer_a_th": "หยุด", "answer_a_en": "Stop",
        "answer_b_no": "Kjøre hvis trygt", "answer_b_th": "ขับต่อได้ถ้าปลอดภัย", "answer_b_en": "Drive if safe",
        "answer_c_no": "Svinge", "answer_c_th": "เลี้ยว", "answer_c_en": "Turn",
        "answer_d_no": "Vente", "answer_d_th": "รอ", "answer_d_en": "Wait",
        "correct_answer": "B",
        "explanation_no": "Du kan kjøre hvis det er klart.",
        "explanation_th": "ขับต่อได้ถ้าปลอดภัย",
        "explanation_en": "You may drive if the way is clear.",
        "category": "Traffic Signs", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig ved parkering?",
        "question_text_th": "อะไรสำคัญเมื่อจอดรถ?",
        "question_text_en": "What is important when parking?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Parkere trygt og lovlig", "answer_b_th": "จอดรถอย่างถูกต้อง", "answer_b_en": "Park safely and legally",
        "answer_c_no": "Ignorere regler", "answer_c_th": "ไม่สนใจกฎ", "answer_c_en": "Ignore rules",
        "answer_d_no": "Stoppe midt i veien", "answer_d_th": "หยุดกลางถนน", "answer_d_en": "Stop in the middle of the road",
        "correct_answer": "B",
        "explanation_no": "Du må parkere riktig og sikkert.",
        "explanation_th": "ต้องจอดรถอย่างถูกต้อง",
        "explanation_en": "You must park correctly and safely.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig ved rygging?",
        "question_text_th": "อะไรสำคัญเมื่อถอยรถ?",
        "question_text_en": "What is important when reversing?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Se bak og rundt", "answer_b_th": "มองด้านหลังให้ดี", "answer_b_en": "Look behind and around",
        "answer_c_no": "Lukke øynene", "answer_c_th": "หลับตา", "answer_c_en": "Close your eyes",
        "answer_d_no": "Ignorere", "answer_d_th": "ไม่สนใจ", "answer_d_en": "Ignore",
        "correct_answer": "B",
        "explanation_no": "Du må ha full kontroll bakover.",
        "explanation_th": "ต้องมองด้านหลังให้ดี",
        "explanation_en": "You must have full control when reversing.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva gjør du ved dårlig sikt?",
        "question_text_th": "คุณทำอย่างไรเมื่อมองเห็นไม่ชัด?",
        "question_text_en": "What do you do in poor visibility?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Senke farten", "answer_b_th": "ลดความเร็ว", "answer_b_en": "Reduce speed",
        "answer_c_no": "Ignorere", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Stoppe alltid", "answer_d_th": "หยุดเสมอ", "answer_d_en": "Always stop",
        "correct_answer": "B",
        "explanation_no": "Lav fart gir bedre kontroll.",
        "explanation_th": "ลดความเร็วเพื่อความปลอดภัย",
        "explanation_en": "Low speed provides better control.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva betyr trafikklys?",
        "question_text_th": "ไฟจราจรหมายถึงอะไร?",
        "question_text_en": "What do traffic lights mean?",
        "answer_a_no": "Ignorere", "answer_a_th": "ไม่สนใจ", "answer_a_en": "Ignore",
        "answer_b_no": "Styre trafikken", "answer_b_th": "ควบคุมการจราจร", "answer_b_en": "Control traffic",
        "answer_c_no": "Kun pynt", "answer_c_th": "แค่ตกแต่ง", "answer_c_en": "Just decoration",
        "answer_d_no": "Valgfritt", "answer_d_th": "เลือกได้", "answer_d_en": "Optional",
        "correct_answer": "B",
        "explanation_no": "Trafikklys regulerer trafikken.",
        "explanation_th": "ไฟจราจรควบคุมการจราจร",
        "explanation_en": "Traffic lights regulate traffic.",
        "category": "Traffic Signs", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig ved sving?",
        "question_text_th": "อะไรสำคัญเมื่อเลี้ยว?",
        "question_text_en": "What is important in curves?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Tilpasse fart", "answer_b_th": "ลดความเร็ว", "answer_b_en": "Adapt speed",
        "answer_c_no": "Ignorere", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Stoppe", "answer_d_th": "หยุด", "answer_d_en": "Stop",
        "correct_answer": "B",
        "explanation_no": "Du må redusere fart i sving.",
        "explanation_th": "ต้องลดความเร็วตอนเลี้ยว",
        "explanation_en": "You must reduce speed in curves.",
        "category": "Road Rules", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva gjør du ved hindring?",
        "question_text_th": "คุณทำอย่างไรเมื่อมีสิ่งกีดขวาง?",
        "question_text_en": "What do you do when encountering an obstacle?",
        "answer_a_no": "Kjøre på", "answer_a_th": "ขับต่อไป", "answer_a_en": "Drive on",
        "answer_b_no": "Stoppe eller unngå", "answer_b_th": "หยุดหรือหลีกเลี่ยง", "answer_b_en": "Stop or avoid",
        "answer_c_no": "Ignorere", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Øke fart", "answer_d_th": "เพิ่มความเร็ว", "answer_d_en": "Increase speed",
        "correct_answer": "B",
        "explanation_no": "Du må unngå hindringer.",
        "explanation_th": "ต้องหลีกเลี่ยงสิ่งกีดขวาง",
        "explanation_en": "You must avoid obstacles.",
        "category": "Safety", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva betyr skilt?",
        "question_text_th": "ป้ายจราจรหมายถึงอะไร?",
        "question_text_en": "What do signs mean?",
        "answer_a_no": "Ignorere", "answer_a_th": "ไม่สนใจ", "answer_a_en": "Ignore",
        "answer_b_no": "Gi informasjon", "answer_b_th": "ให้ข้อมูลสำคัญ", "answer_b_en": "Provide information",
        "answer_c_no": "Kun pynt", "answer_c_th": "แค่ตกแต่ง", "answer_c_en": "Just decoration",
        "answer_d_no": "Valgfritt", "answer_d_th": "เลือกได้", "answer_d_en": "Optional",
        "correct_answer": "B",
        "explanation_no": "Skilt gir viktige regler.",
        "explanation_th": "ป้ายให้ข้อมูลสำคัญ",
        "explanation_en": "Signs provide important rules and information.",
        "category": "Traffic Signs", "difficulty": "easy",
    },
    {
        "question_text_no": "Hva er viktig i trafikk?",
        "question_text_th": "อะไรสำคัญในจราจร?",
        "question_text_en": "What is important in traffic?",
        "answer_a_no": "Kjøre fort", "answer_a_th": "ขับเร็ว", "answer_a_en": "Drive fast",
        "answer_b_no": "Være oppmerksom", "answer_b_th": "มีสมาธิ", "answer_b_en": "Be attentive",
        "answer_c_no": "Ignorere", "answer_c_th": "ไม่สนใจ", "answer_c_en": "Ignore",
        "answer_d_no": "Kun følge GPS", "answer_d_th": "ตาม GPS เท่านั้น", "answer_d_en": "Only follow GPS",
        "correct_answer": "B",
        "explanation_no": "Oppmerksomhet er viktig.",
        "explanation_th": "ต้องมีสมาธิในการขับ",
        "explanation_en": "Attention is essential in traffic.",
        "category": "Safety", "difficulty": "easy",
    },
]

async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    inserted = 0
    skipped = 0
    for q in NEW_QUESTIONS:
        # Check duplicate by Norwegian question text
        existing = await db.questions.find_one({"question_text_no": q["question_text_no"]})
        if existing:
            skipped += 1
            continue

        doc = {
            "id": str(uuid.uuid4()),
            **q,
            "image_url": None,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.questions.insert_one(doc)
        inserted += 1

    print(f"Done! Inserted: {inserted}, Skipped (duplicates): {skipped}")
    total = await db.questions.count_documents({})
    print(f"Total questions in database: {total}")
    client.close()

asyncio.run(seed())
